# Generated by Django 5.1 on 2025-04-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_account_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Картинка'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ')], max_length=255, null=True, verbose_name='Тип')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('upload_file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='files', related_query_name='files', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_creators', related_query_name='file_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_editors', related_query_name='file_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'permissions': (('add_file', 'Может добавить файл'), ('change_file', 'Может изменить файл'), ('delete_file', 'Может удалить файл'), ('view_file', 'Может просматривать файл')),
                'default_permissions': (),
            },
        ),
    ]
