# Generated by Django 5.1 on 2025-06-11 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_accountsgroup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_selection', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('sorting', 'Сортировка'), ('compliance', 'Соотвествие'), ('text_input', 'Текстовый ввод'), ('numeric_input', 'Числовой ввод')], default='', max_length=255, verbose_name='Тип вопроса')),
                ('manual', models.TextField(verbose_name='Инструкция')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='questions_picture/', verbose_name='Картинка вопроса')),
                ('score', models.PositiveIntegerField(verbose_name='Балл')),
                ('feedback_for_correct', models.TextField(default='Верно!', verbose_name='Обратная связь при правильном ответе')),
                ('feedback_for_incorrect', models.TextField(default='Неверно!', verbose_name='Обратная связь при неправильном ответе')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='questions', related_query_name='question', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_creators', related_query_name='question_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_editors', related_query_name='question_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'permissions': (('add_question', 'Может добавить вопрос'), ('change_question', 'Может изменить вопрос'), ('delete_question', 'Может удалить вопрос'), ('view_question', 'Может просматривать вопрос')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(db_index=True, verbose_name='Позиция в списке')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='answer_picture/', verbose_name='Картинка ответа')),
                ('score', models.PositiveIntegerField(verbose_name='Балл')),
                ('feedback_for_correct', models.TextField(default='Верно!', verbose_name='Обратная связь при правильном ответе')),
                ('feedback_for_incorrect', models.TextField(default='Неверно!', verbose_name='Обратная связь при неправильном ответе')),
                ('correct_answer', models.BooleanField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('correct_item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Правильная позиция')),
                ('correct_text_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='Правильный ответ')),
                ('correct_numeric_input', models.IntegerField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_creators', related_query_name='answer_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_editors', related_query_name='answer_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'permissions': (('add_answer', 'Может добавить ответ'), ('change_answer', 'Может изменить ответ'), ('delete_answer', 'Может удалить ответ'), ('view_answer', 'Может просматривать ответ')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RelevantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_point', related_query_name='relevant_point', to='tests.answer', verbose_name='Ответ')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevant_point_creators', related_query_name='relevant_point_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevant_point_editors', related_query_name='relevant_point_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Соответствующий пункт',
                'verbose_name_plural': 'Соответствующие пункты',
                'permissions': (('add_relevant_point', 'Может добавить соответствующий пункт'), ('change_relevant_point', 'Может изменить соответствующий пункт'), ('delete_relevant_point', 'Может удалить соответствующий пункт'), ('view_relevant_point', 'Может просматривать соответствующий пункт')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='test_avatars/', verbose_name='Аватар')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('passing_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на выполнение (минут)')),
                ('random_questions', models.BooleanField(default=True, verbose_name='Случайный порядок вопросов')),
                ('random_answers', models.BooleanField(default=True, verbose_name='Случайный порядок ответов')),
                ('show_questions_results', models.BooleanField(default=True, verbose_name='Показывать результаты вопросов')),
                ('show_answers_results', models.BooleanField(default=True, verbose_name='Показывать результаты ответов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='tests', related_query_name='test', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_creators', related_query_name='test_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_editors', related_query_name='test_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тест',
                'permissions': (('add_test', 'Может добавить тест'), ('change_test', 'Может изменить тест'), ('delete_test', 'Может удалить тест'), ('view_test', 'Может просматривать тест')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(verbose_name='Пункт')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('sample_size', models.PositiveIntegerField(verbose_name='Количество вопросов в выборке')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_section_creators', related_query_name='test_section_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_section_editors', related_query_name='test_section_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests_questions', related_query_name='tests_questions', to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Раздел теста',
                'verbose_name_plural': 'Разделы теста',
                'permissions': (('add_test_section', 'Может добавить раздел теста'), ('change_test_section', 'Может изменить раздел теста'), ('delete_test_section', 'Может удалить раздел теста'), ('view_test_section', 'Может просматривать раздел теста')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TestSectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(verbose_name='Пункт')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_section_question_creators', related_query_name='test_section_question_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_section_question_editors', related_query_name='test_section_question_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_section_questions', related_query_name='test_section_question', to='tests.question', verbose_name='Вопрос')),
                ('test_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_section_questions', related_query_name='test_section_question', to='tests.testsection', verbose_name='Раздел теста')),
            ],
            options={
                'verbose_name': 'Вопрос раздела теста',
                'verbose_name_plural': 'Вопросы раздела теста',
                'permissions': (('add_test_section_question', 'Может добавить вопрос раздела теста'), ('change_test_section_question', 'Может изменить вопрос раздела теста'), ('delete_test_section_question', 'Может удалить вопрос раздела теста'), ('view_test_section_question', 'Может просматривать вопрос раздела теста')),
                'default_permissions': (),
            },
        ),
    ]
