# Generated by Django 5.1 on 2025-06-13 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_testsection_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsection',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sections', related_query_name='test_section', to='tests.test', verbose_name='Тест'),
        ),
    ]
