# Generated by Django 5.1 on 2025-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_testsection_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Попытки'),
        ),
    ]
