# Generated by Django 5.1 on 2025-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
    ]
