# Generated by Django 5.1 on 2025-12-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_answer_score_alter_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='self_assignment',
            field=models.BooleanField(default=False, verbose_name='Самоназначение'),
        ),
    ]
