# Generated by Django 5.1 on 2026-02-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_test_self_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'default_permissions': (), 'permissions': (('add_test', 'Может добавить тест'), ('change_test', 'Может изменить тест'), ('delete_test', 'Может удалить тест'), ('view_test', 'Может просматривать тест')), 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
