# Generated by Django 5.1 on 2026-02-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_test_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'default_permissions': (), 'permissions': (('add_question', 'Может добавить вопрос теста'), ('change_question', 'Может изменить вопрос теста'), ('delete_question', 'Может удалить вопрос теста'), ('view_question', 'Может просматривать вопрос теста')), 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы теста'},
        ),
    ]
