# Generated by Django 5.1 on 2025-10-15 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpms', '0043_eventresult_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_tasks_tracking', models.BooleanField(default=True, verbose_name='Отслеживание своих задач')),
                ('controlled_tasks_tracking', models.BooleanField(default=True, verbose_name='Отслеживание задач на контроле')),
                ('observed_tasks_tracking', models.BooleanField(default=True, verbose_name='Отслеживание задач под наблюдением')),
                ('self_tasks_reminder_period', models.PositiveIntegerField(default=1, verbose_name='Период напоминания для своих задач (дней)')),
                ('controlled_tasks_reminder_period', models.PositiveIntegerField(default=3, verbose_name='Период напоминания для задач на контроле (дней)')),
                ('observed_tasks_reminder_period', models.PositiveIntegerField(default=7, verbose_name='Период напоминания для задач под наблюдением (дней)')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_settings', related_query_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
                'permissions': (('add_notification_settings', 'Может добавлять настройки уведомлений'), ('change_notification_settings', 'Может изменить настройки уведомлений'), ('delete_notification_settings', 'Может удалить настройки уведомлений'), ('view_notification_settings', 'Может просматривать настройки уведомлений')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, choices=[('task_assigned', 'Назначение задачи'), ('task_reminder', 'Напоминание о задаче'), ('task_completed', 'Выполнение задачи'), ('task_failed', 'Провал задачи'), ('task_canceled', 'Отмена задачи')], max_length=50, null=True, verbose_name='Тип оповещения')),
                ('tracking', models.BooleanField(default=False, verbose_name='Отслеживание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notifications', related_query_name='task_notification', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Оповещение о задаче',
                'verbose_name_plural': 'Оповещения о задаче',
                'permissions': (('add_task_notification', 'Может добавить оповещение о задаче'), ('change_task_notification', 'Может изменить оповещение о задаче'), ('delete_task_notification', 'Может удалить оповещение о задаче'), ('view_task_notification', 'Может просматривать оповещение о задаче')),
                'default_permissions': (),
            },
        ),
    ]
