# Generated by Django 5.1 on 2025-10-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='changed',
        ),
    ]
