# Generated by Django 5.1 on 2025-10-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationsettings_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknotification',
            name='tracking',
        ),
        migrations.AddField(
            model_name='tasknotification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
