# Generated by Django 5.1 on 2025-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_tasknotification_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('task_created', 'Создание задачи'), ('task_reminder', 'Напоминание о задаче'), ('task_completed', 'Выполнение задачи'), ('task_failed', 'Провал задачи'), ('task_canceled', 'Отмена задачи')], max_length=50, null=True, verbose_name='Тип оповещения'),
        ),
    ]
