# Generated by Django 5.1 on 2025-03-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0002_initial'),
        ('chats', '0003_chat_task_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(blank=True, choices=[('common_chat', 'Обычный чат'), ('task_chat', 'Чат задачи'), ('queue_chat', 'Чат очереди')], max_length=20, null=True, verbose_name='Тип чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', related_query_name='chat', to='bpms.queue', verbose_name='Очередь'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', related_query_name='chat', to='bpms.task', verbose_name='Задача'),
        ),
    ]
