# Generated by Django 5.1 on 2025-03-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_chat_type_chat_queue_alter_chat_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'default_permissions': (), 'permissions': (('add_сhat', 'Может добавить чат'), ('change_сhat', 'Может изменить чат'), ('delete_сhat', 'Может удалить чат'), ('view_сhat', 'Может просматривать чат')), 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': (), 'permissions': (('add_message', 'Может добавить сообщение'), ('change_message', 'Может изменить сообщение'), ('delete_message', 'Может удалить сообщение'), ('view_message', 'Может просматривать сообщение')), 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
