# Generated by Django 5.1 on 2025-03-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chat_desc_alter_chat_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'default_permissions': (), 'permissions': (('add_chat', 'Может добавить чат'), ('change_chat', 'Может изменить чат'), ('delete_chat', 'Может удалить чат'), ('view_chat', 'Может просматривать чат')), 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
