# Generated by Django 5.1 on 2025-03-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': (), 'permissions': (('add_message', 'Может добавить сообщение'), ('change_message', 'Может изменить сообщение'), ('delete_message', 'Может удалить сообщение'), ('view_message', 'Может просматривать сообщение')), 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
    ]
