# Generated by Django 5.1 on 2025-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
