# Generated by Django 5.1 on 2025-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_remove_message_recipient'),
        ('core', '0003_alter_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='chats', related_query_name='chat', to='core.category', verbose_name='Категории'),
        ),
    ]
