# Generated by Django 5.1 on 2026-01-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_chat_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_type',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='task',
        ),
    ]
