# Generated by Django 5.1 on 2025-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(blank=True, choices=[('task_outcome', 'Результат задачи'), ('trigger', 'Триггер')], max_length=50, null=True, verbose_name='Тип работы')),
                ('object_type', models.CharField(blank=True, choices=[('client', 'Клиент'), ('account', 'Аккаунт')], max_length=50, null=True, verbose_name='Тип объекта')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Управляющий элемент',
                'verbose_name_plural': 'Управляющие элементы',
                'permissions': (('add_control_element', 'Может добавить управляющий элемент'), ('change_control_element', 'Может изменить управляющий элемент'), ('delete_control_element', 'Может удалить управляющий элемент'), ('view_control_element', 'Может просматривать управляющий элемент')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ControlElementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пункт')),
                ('action_type', models.CharField(blank=True, choices=[('change_task_status', 'Изменить статус задачи'), ('change_task_outcome', 'Изменить итог задачи'), ('assign_task', 'Назначить задачу'), ('add_task_to_queue', 'Добавить задачу в очередь'), ('new_interaction', 'Новое взаимодействие')], max_length=50, null=True, verbose_name='Действия')),
                ('task_status', models.CharField(blank=True, choices=[('waiting', 'В ожидании'), ('assigned', 'Назначена'), ('in_progress', 'В процессе'), ('under_review', 'На проверке'), ('completed', 'Выполнена'), ('failed', 'Провалена'), ('canceled', 'Отменена')], max_length=50, null=True, verbose_name='Статус задачи')),
                ('executor_type', models.CharField(blank=True, choices=[('current_executor', 'Текущий исполнитель'), ('selected_executor', 'Выбранный исполнитель'), ('none', 'Без исполнителя')], max_length=50, null=True, verbose_name='Тип исполнителя')),
                ('manager_control', models.BooleanField(default=False, verbose_name='Контроль руководителей')),
                ('assignment_condition', models.CharField(blank=True, choices=[('any_case', 'В любом случае'), ('not_assigned', 'Не была назначена'), ('not_completed', 'Не была выполнена')], max_length=50, null=True, verbose_name='Условия назначения')),
                ('delay_type', models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('none', 'Без задержки')], max_length=50, null=True, verbose_name='Тип задержки')),
                ('delay_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Задержка')),
                ('interaction_frame', models.CharField(blank=True, choices=[('current', 'Текущее'), ('all', 'Все')], max_length=50, null=True, verbose_name='Рамки взаимодействия')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'permissions': (('add_control_element_action', 'Может добавить действие'), ('change_control_element_action', 'Может изменить действие'), ('delete_control_element_action', 'Может удалить действие'), ('view_control_element_action', 'Может просматривать действие')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ControlElementActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Срабатывание управляющего элемента',
                'verbose_name_plural': 'Срабатывания управляющих элементов',
                'permissions': (('add_control_element_activation', 'Может добавить срабатывание управляющего элемента'), ('change_control_element_activation', 'Может изменить срабатывание управляющего элемента'), ('delete_control_element_activation', 'Может удалить срабатывание управляющего элемента'), ('view_control_element_activation', 'Может просматривать срабатывание управляющего элемента')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ControlElementCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пункт')),
                ('condition_type', models.CharField(choices=[('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи')], max_length=50, verbose_name='Условие')),
                ('comparison_operator', models.CharField(choices=[('equal', 'Равно'), ('not_equal', 'Не равно')], max_length=50, verbose_name='Оператор сравнения')),
                ('task_status', models.CharField(blank=True, choices=[('waiting', 'В ожидании'), ('assigned', 'Назначена'), ('in_progress', 'В процессе'), ('under_review', 'На проверке'), ('completed', 'Выполнена'), ('failed', 'Провалена'), ('canceled', 'Отменена')], max_length=50, null=True, verbose_name='Статус задачи')),
                ('interaction_frame', models.CharField(blank=True, choices=[('current', 'Текущее'), ('all', 'Все')], max_length=50, null=True, verbose_name='Рамки взаимодействий')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
                'permissions': (('add_control_element_condition', 'Может добавить условие для управляющего элемента'), ('change_control_element_condition', 'Может изменить условие для управляющего элемента'), ('delete_control_element_condition', 'Может удалить условие для управляющего элемента'), ('view_control_element_condition', 'Может просматривать условие для управляющего элемента')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ControlElementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('client_created', 'Клиент создан'), ('account_created', 'Аккаунт создан'), ('task_created', 'Задача создана'), ('task_status_changed', 'Изменился статус задачи'), ('task_outcome_changed', 'Изменился итог задачи'), ('trigger_fired', 'Сработал триггер')], max_length=50, verbose_name='Событие')),
                ('interaction_frame', models.CharField(blank=True, choices=[('current', 'Текущее'), ('all', 'Все')], max_length=50, null=True, verbose_name='Рамки взаимодействий')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'permissions': (('add_control_element_event', 'Может добавить событие управляющего элемента'), ('change_control_element_event', 'Может изменить событие управляющего элемента'), ('delete_control_element_event', 'Может удалить событие управляющего элемента'), ('view_control_element_event', 'Может просматривать событие управляющего элемента')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, choices=[('client', 'Клиент'), ('account', 'Аккаунт')], max_length=50, null=True, verbose_name='Тип объекта')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'permissions': (('add_interaction', 'Может добавить взаимодействие'), ('change_interaction', 'Может изменить взаимодействие'), ('delete_interaction', 'Может удалить взаимодействие'), ('view_interaction', 'Может просматривать взаимодействие')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PlanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначен'), ('in_progress', 'В процессе'), ('completed', 'Выполнена'), ('failed', 'Провалена'), ('canceled', 'Отменен')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Результат плана',
                'verbose_name_plural': 'Результаты планов',
                'permissions': (('add_plan_result', 'Может добавить результат плана'), ('change_plan_result', 'Может изменить результат плана'), ('delete_plan_result', 'Может удалить результат плана'), ('view_plan_result', 'Может просматривать результат плана')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('auto_assignment', models.BooleanField(default=False, verbose_name='Автоназначение исполнителя')),
                ('last_executor_item', models.PositiveIntegerField(default=0, verbose_name='Номер последнего исполнителя')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Очередь',
                'verbose_name_plural': 'Очереди',
                'permissions': (('add_queue', 'Может добавить очередь'), ('change_queue', 'Может изменить очередь'), ('delete_queue', 'Может удалить очередь'), ('view_queue', 'Может просматривать очередь')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QueueExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(verbose_name='Пункт')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Исполнитель в очереди',
                'verbose_name_plural': 'Исполнители в очереди',
                'permissions': (('add_queue_executor', 'Может добавить исполнителя в очередь'), ('change_queue_executor', 'Может изменить исполнителя в очереди'), ('delete_queue_executor', 'Может удалить исполнителя из очереди'), ('view_queue_executor', 'Может просматривать исполнителя в очереди')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QueueTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(verbose_name='Пункт')),
                ('status', models.CharField(choices=[('waiting_for_executor', 'Ожидает исполнителя'), ('executor_assigned', 'Исполнитель назначен')], default='waiting_for_executor', max_length=50, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Задача в очереди',
                'verbose_name_plural': 'Задачи в очереди',
                'permissions': (('add_queue_task', 'Может добавить задачу в очередь'), ('change_queue_task', 'Может изменить задачу в очереди'), ('delete_queue_task', 'Может удалить задачу из очереди'), ('view_queue_task', 'Может просматривать задачу в очереди')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, choices=[('client', 'Клиент'), ('account', 'Аккаунт')], max_length=50, null=True, verbose_name='Тип объекта')),
                ('is_child', models.BooleanField(default=False, verbose_name='Дочерняя')),
                ('item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пункт')),
                ('task_type', models.CharField(blank=True, choices=[('common_task', 'Обычная задача'), ('plan_implementation', 'Реализация плана'), ('material_review', 'Ознакомление с материалом'), ('test_taking', 'Прохождение теста'), ('course_study', 'Изучение курса'), ('event_participation', 'Участие в мероприятии')], max_length=50, null=True, verbose_name='Тип задачи')),
                ('require_review', models.BooleanField(default=False, verbose_name='Требуется проверка')),
                ('manual', models.TextField(blank=True, null=True, verbose_name='Инструкция')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('term', models.BooleanField(default=False, verbose_name='Сроки')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало по плану')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец по плану')),
                ('waiting', models.BooleanField(default=False, verbose_name='Ожидает активации')),
                ('task_outcome', models.BooleanField(default=False, verbose_name='Итог задачи')),
                ('executor_outcome', models.BooleanField(default=False, verbose_name='Исполнитель подводит итог')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'permissions': (('add_task', 'Может добавить задачу'), ('change_task', 'Может изменить задачу'), ('delete_task', 'Может удалить задачу'), ('view_task', 'Может просматривать задачу')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_scaled', models.PositiveIntegerField(blank=True, null=True, verbose_name='Масштабированный балл (%)')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначена'), ('in_progress', 'В процессе'), ('under_review', 'На проверке'), ('completed', 'Выполнена'), ('failed', 'Провалена'), ('canceled', 'Отменена')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Результат работы',
                'verbose_name_plural': 'Результаты работы',
                'permissions': (('add_task_result', 'Может добавить результат задачи'), ('change_task_result', 'Может изменить результат задачи'), ('delete_task_result', 'Может удалить результат задачи'), ('view_task_result', 'Может просматривать результат задачи')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, choices=[('client', 'Клиент'), ('account', 'Аккаунт')], max_length=50, null=True, verbose_name='Тип объекта')),
                ('is_child', models.BooleanField(default=False, verbose_name='Дочерняя')),
                ('item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пункт')),
                ('delay_type', models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('none', 'Без задержки')], max_length=20, null=True, verbose_name='Тип задержки')),
                ('delay_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Задержка')),
                ('task_type', models.CharField(blank=True, choices=[('common_task', 'Обычная задача'), ('plan_implementation', 'Реализация плана'), ('material_review', 'Ознакомление с материалом'), ('test_taking', 'Прохождение теста'), ('course_study', 'Изучение курса'), ('event_participation', 'Участие в мероприятии')], max_length=50, null=True, verbose_name='Тип задачи')),
                ('manual', models.TextField(blank=True, null=True, verbose_name='Инструкция')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('require_review', models.BooleanField(default=False, verbose_name='Требуется проверка')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('term_type', models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('none', 'Без срока')], max_length=20, null=True, verbose_name='Тип срока')),
                ('term_value', models.IntegerField(blank=True, null=True, verbose_name='Срок')),
                ('waiting', models.BooleanField(default=False, verbose_name='Ожидает активации')),
                ('task_outcome', models.BooleanField(default=False, verbose_name='Итог задачи')),
                ('executor_outcome', models.BooleanField(default=False, verbose_name='Исполнитель подводит итог')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
                'permissions': (('add_task_template', 'Может добавить шаблон задачи'), ('change_task_template', 'Может изменить шаблон задачи'), ('delete_task_template', 'Может удалить шаблон задачи'), ('view_task_template', 'Может просматривать шаблон задачи')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('object_type', models.CharField(blank=True, choices=[('client', 'Клиент'), ('account', 'Аккаунт')], max_length=50, null=True, verbose_name='Тип объекта')),
                ('last_executor_interaction', models.BooleanField(default=False, verbose_name='Последнее взаимодействие с исполнителем')),
                ('executor_type', models.CharField(blank=True, choices=[('selected', 'Выбранному исполнителю'), ('group', 'Группе исполнителей'), ('none', 'Без исполнителей')], max_length=50, null=True, verbose_name='Тип исполнителя')),
                ('manager_control', models.BooleanField(default=False, verbose_name='Контроль руководителей')),
                ('assignment_condition', models.CharField(blank=True, choices=[('any_case', 'В любом случае'), ('not_assigned', 'Не была назначена'), ('not_completed', 'Не была выполнена')], max_length=50, null=True, verbose_name='Условия назначения')),
                ('interaction_frame', models.CharField(blank=True, choices=[('current', 'Текущее'), ('all', 'Все')], max_length=50, null=True, verbose_name='Рамки взаимодействий')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало по плану')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Назначение шаблона задачи',
                'verbose_name_plural': 'Назначения шаблонов задач',
                'permissions': (('add_task_template_assignment', 'Может добавить назначение шаблона задачи'), ('change_task_template_assignment', 'Может изменить назначение шаблона задачи'), ('delete_task_template_assignment', 'Может удалить назначение шаблона задачи'), ('view_task_template_assignment', 'Может просматривать назначение шаблона задачи')),
                'default_permissions': (),
            },
        ),
    ]
