# Generated by Django 5.1 on 2025-03-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpms', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelement',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='control_elements', related_query_name='control_element', to='core.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='controlelement',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_element_creators', related_query_name='control_element_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='controlelement',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_element_editors', related_query_name='control_element_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='control_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', related_query_name='action', to='bpms.controlelement', verbose_name='Управляющий элемент'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='controller_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_controller_group_actions', related_query_name='assignment_controller_group_action', to='core.accountsgroup', verbose_name='Группа контролеров'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_creators', related_query_name='action_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_editors', related_query_name='action_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_executor_actions', related_query_name='assignment_executor_action', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='observer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_observer_group_actions', related_query_name='assignment_observer_group_action', to='core.accountsgroup', verbose_name='Группа наблюдателей'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='task_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_outcome_actions', related_query_name='task_outcome_action', to='bpms.controlelement', verbose_name='Итог задачи'),
        ),
        migrations.AddField(
            model_name='controlelementactivation',
            name='control_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', related_query_name='activation', to='bpms.controlelement', verbose_name='Управляющий элемент'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='control_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', related_query_name='condition', to='bpms.controlelement', verbose_name='Управляющий элемент'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions_creators', related_query_name='condition_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions_editors', related_query_name='condition_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='task_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_outcome_conditions', related_query_name='task_outcome_condition', to='bpms.controlelement', verbose_name='Итог задачи'),
        ),
        migrations.AddField(
            model_name='controlelementevent',
            name='control_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='event', to='bpms.controlelement', verbose_name='Управляющий элемент'),
        ),
        migrations.AddField(
            model_name='controlelementevent',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_creators', related_query_name='event_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='controlelementevent',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_editors', related_query_name='event_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='controlelementevent',
            name='fired_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fired_trigger_events', related_query_name='fired_trigger_event', to='bpms.controlelement', verbose_name='Сработавший триггер'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', related_query_name='interaction', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', related_query_name='interaction', to='core.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_creators', related_query_name='interaction_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editors', related_query_name='interaction_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='controlelementactivation',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_element_activations', related_query_name='control_element_activation', to='bpms.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AddField(
            model_name='planresult',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_result_creators', related_query_name='plan_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='planresult',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_result_editors', related_query_name='plan_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='planresult',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_results', related_query_name='plan_result', to='bpms.controlelement', verbose_name='Итог задачи'),
        ),
        migrations.AddField(
            model_name='queue',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='queues', related_query_name='queue', to='core.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='queue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_creators', related_query_name='queue_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='queue',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_editors', related_query_name='queue_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_actions', related_query_name='queued_action', to='bpms.queue', verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='queueexecutor',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_executor_creators', related_query_name='queue_executor_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='queueexecutor',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_executor_editors', related_query_name='queue_executor_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='queueexecutor',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_executors', related_query_name='queue_executor', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.AddField(
            model_name='queueexecutor',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_executors', related_query_name='queue_executor', to='bpms.queue', verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='queuetask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_task_creators', related_query_name='queue_task_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='queuetask',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_task_editors', related_query_name='queue_task_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='queuetask',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queue_tasks', related_query_name='assigned_queue_task', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='queuetask',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tasks', related_query_name='queue_task', to='bpms.queue', verbose_name='Очередь'),
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tasks', related_query_name='task', to='core.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='task',
            name='co_executor_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_co_executor_group', related_query_name='task_co_executor_group', to='core.accountsgroup', verbose_name='Группа соисполнителей'),
        ),
        migrations.AddField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(blank=True, related_name='task_co_executors', related_query_name='task_co_executor', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители'),
        ),
        migrations.AddField(
            model_name='task',
            name='controller_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_controller_group', related_query_name='task_controller_group', to='core.accountsgroup', verbose_name='Группа контролеров'),
        ),
        migrations.AddField(
            model_name='task',
            name='controllers',
            field=models.ManyToManyField(blank=True, related_name='task_controllers', related_query_name='task_controller', to=settings.AUTH_USER_MODEL, verbose_name='Контролеры'),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creators', related_query_name='task_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='task',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_editors', related_query_name='task_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_executors', related_query_name='task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', related_query_name='task', to='bpms.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AddField(
            model_name='task',
            name='observer_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_observer_group', related_query_name='task_observer_group', to='core.accountsgroup', verbose_name='Группа наблюдателей'),
        ),
        migrations.AddField(
            model_name='task',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='task_observers', related_query_name='task_observer', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', related_query_name='child_task', to='bpms.task', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='queuetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tasks', related_query_name='queue_task', to='bpms.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='planresult',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_result', related_query_name='plan_result', to='bpms.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='controlelementactivation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', related_query_name='activation', to='bpms.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_result_creators', related_query_name='task_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_result_editors', related_query_name='task_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_results', related_query_name='task_result', to='bpms.controlelement', verbose_name='Итог задачи'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_result', related_query_name='task_result', to='bpms.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='task_templates', related_query_name='task_template', to='core.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_creators', related_query_name='task_template_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_editors', related_query_name='task_template_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', related_query_name='child_task', to='bpms.tasktemplate', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_tasks', related_query_name='task_template_task', to='bpms.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AddField(
            model_name='controlelementevent',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to='bpms.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', related_query_name='condition', to='bpms.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', related_query_name='action', to='bpms.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AddField(
            model_name='controlelement',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_control_elements', related_query_name='task_template_control_element', to='bpms.tasktemplate', verbose_name='Шаблон задачи'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='task_template_assignments', related_query_name='task_template_assignment', to='core.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='controller_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignment_controllers', related_query_name='task_template_assignment_controller', to='core.accountsgroup', verbose_name='Группа контролеров'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignment_creators', related_query_name='task_template_assignment_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignment_editors', related_query_name='task_template_assignment_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignment_individual_executors', related_query_name='task_template_assignment_individual_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='executor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignment_executors', related_query_name='task_template_assignment_executor', to='core.accountsgroup', verbose_name='Группа исполнителей'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignments', related_query_name='task_template_assignment', to='bpms.interaction', verbose_name='Взаимодействие'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='observer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_assignment_observers', related_query_name='task_template_assignment_observer', to='core.accountsgroup', verbose_name='Группа наблюдателей'),
        ),
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_template_assignments', related_query_name='task_template_assignment', to='bpms.tasktemplate', verbose_name='Шаблон задачи'),
        ),
    ]
