# Generated by Django 5.1 on 2025-05-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0002_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='materials.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', related_query_name='task_template', to='materials.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_tasks', related_query_name='child_task', to='bpms.task', verbose_name='План'),
        ),
    ]
