# Generated by Django 5.1 on 2025-05-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0003_task_material_tasktemplate_material_alter_task_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplateassignment',
            name='last_executor_interaction',
        ),
        migrations.RemoveField(
            model_name='tasktemplateassignment',
            name='object_type',
        ),
    ]
