# Generated by Django 5.1 on 2025-05-04 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0004_remove_tasktemplateassignment_last_executor_interaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planresult',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('under_review', 'На проверке'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='MaterialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_result_creators', related_query_name='material_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_result_editors', related_query_name='material_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_results', related_query_name='material_result', to='bpms.controlelement', verbose_name='Итог задачи')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_result', related_query_name='material_result', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат материала',
                'verbose_name_plural': 'Результаты материала',
                'permissions': (('add_material_result', 'Может добавить результат материала'), ('change_material_result', 'Может изменить результат материала'), ('delete_material_result', 'Может удалить результат материала'), ('view_material_result', 'Может просматривать результат материала')),
                'default_permissions': (),
            },
        ),
    ]
