# Generated by Django 5.1 on 2025-05-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0005_alter_planresult_status_alter_taskresult_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='term',
            new_name='deadline',
        ),
    ]
