# Generated by Django 5.1 on 2025-05-09 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0006_rename_term_task_deadline'),
        ('core', '0004_alter_accountsgroup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='co_executor_group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='co_executors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.AddField(
            model_name='task',
            name='executor_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_executor_group', related_query_name='task_executor_group', to='core.accountsgroup', verbose_name='Группа исполнителей'),
        ),
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='task_executors', related_query_name='task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='tasktemplateassignment',
            name='executor_type',
            field=models.CharField(blank=True, choices=[('selected', 'Выбранным исполнителям'), ('group', 'Группе исполнителей'), ('none', 'Без исполнителей')], max_length=50, null=True, verbose_name='Тип исполнителя'),
        ),
    ]
