# Generated by Django 5.1 on 2025-05-09 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0007_remove_task_co_executor_group_and_more'),
        ('core', '0005_alter_accountsgroup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor_group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executors',
        ),
        migrations.AddField(
            model_name='task',
            name='co_executor_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_co_executor_group', related_query_name='task_co_executor_group', to='core.accountsgroup', verbose_name='Группа соисполнителей'),
        ),
        migrations.AddField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(blank=True, related_name='task_co_executors', related_query_name='task_co_executor', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_executors', related_query_name='task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='tasktemplateassignment',
            name='executor_type',
            field=models.CharField(blank=True, choices=[('selected', 'Выбранному исполнителю'), ('group', 'Группе исполнителей'), ('none', 'Без исполнителей')], max_length=50, null=True, verbose_name='Тип исполнителя'),
        ),
    ]
