# Generated by Django 5.1 on 2025-05-09 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0008_remove_task_executor_group_remove_task_executors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', related_query_name='child_task', to='bpms.task', verbose_name='План'),
        ),
    ]
