# Generated by Django 5.1 on 2025-05-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0009_alter_task_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementevent',
            name='event_type',
            field=models.CharField(choices=[('client_created', 'Клиент создан'), ('account_created', 'Аккаунт создан'), ('task_created', 'Задача создана'), ('child_task_status_changed', 'Изменился статус дочерней задачи'), ('task_status_changed', 'Изменился статус задачи'), ('task_outcome_changed', 'Изменился итог задачи'), ('trigger_fired', 'Сработал триггер')], max_length=50, verbose_name='Событие'),
        ),
    ]
