# Generated by Django 5.1 on 2025-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0010_alter_controlelementevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи')], max_length=50, verbose_name='Условие'),
        ),
    ]
