# Generated by Django 5.1 on 2025-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0012_alter_controlelementevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelement',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='object_type',
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='score_scaled',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл (%)'),
        ),
    ]
