# Generated by Django 5.1 on 2025-05-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0013_remove_controlelement_object_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor_outcome',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='executor_outcome',
        ),
    ]
