# Generated by Django 5.1 on 2025-06-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0014_remove_task_executor_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_outcome',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='task_outcome',
        ),
    ]
