# Generated by Django 5.1 on 2025-06-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0015_remove_task_task_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_outcome',
            field=models.BooleanField(default=False, verbose_name='Итог задачи'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='task_outcome',
            field=models.BooleanField(default=False, verbose_name='Итог задачи'),
        ),
    ]
