# Generated by Django 5.1 on 2025-06-06 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0016_task_task_outcome_tasktemplate_task_outcome'),
        ('courses', '0002_remove_course_type_remove_course_zip_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='courses.course', verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField(default='{}', verbose_name='Прогресс')),
                ('score_scaled', models.PositiveIntegerField(blank=True, null=True, verbose_name='Балл (%)')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_result_creators', related_query_name='course_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_result_editors', related_query_name='course_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_results', related_query_name='course_result', to='bpms.controlelement', verbose_name='Итог задачи')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_result', related_query_name='course_result', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат материала',
                'verbose_name_plural': 'Результаты материала',
                'permissions': (('add_course_result', 'Может добавить результат материала'), ('change_course_result', 'Может изменить результат материала'), ('delete_course_result', 'Может удалить результат материала'), ('view_course_result', 'Может просматривать результат материала')),
                'default_permissions': (),
            },
        ),
    ]
