# Generated by Django 5.1 on 2025-06-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0017_task_course_courseresult'),
        ('courses', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', related_query_name='task_template', to='courses.course', verbose_name='Курс'),
        ),
    ]
