# Generated by Django 5.1 on 2025-06-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0018_tasktemplate_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresult',
            options={'default_permissions': (), 'permissions': (('add_course_result', 'Может добавить результат курса'), ('change_course_result', 'Может изменить результат курса'), ('delete_course_result', 'Может удалить результат курса'), ('view_course_result', 'Может просматривать результат курса')), 'verbose_name': 'Результат курса', 'verbose_name_plural': 'Результаты курса'},
        ),
    ]
