# Generated by Django 5.1 on 2025-06-26 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0019_alter_courseresult_options'),
        ('tests', '0004_test_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='assigned', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_result_creators', related_query_name='question_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_result_editors', related_query_name='question_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_results', related_query_name='question_result', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Результат вопроса',
                'verbose_name_plural': 'Результаты вопроса',
                'permissions': (('add_question_result', 'Может добавить результат вопроса'), ('change_question_result', 'Может изменить результат вопроса'), ('delete_question_result', 'Может удалить результат вопроса'), ('view_question_result', 'Может просматривать результат вопроса')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AnswerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.BooleanField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('selected_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Правильная позиция')),
                ('selected_text_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='Правильный ответ')),
                ('selected_numeric_input', models.IntegerField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='assigned', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_results', related_query_name='answer_result', to='tests.answer', verbose_name='Ответ')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_result_creators', related_query_name='answer_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_result_editors', related_query_name='answer_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('selected_relevant_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers_results', related_query_name='answers_result', to='tests.relevantpoint', verbose_name='Соответствующий пункт')),
                ('question_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_result', related_query_name='answer_results', to='bpms.questionresult', verbose_name='Результат вопроса')),
            ],
            options={
                'verbose_name': 'Результат ответа',
                'verbose_name_plural': 'Результаты ответа',
                'permissions': (('add_answer_result', 'Может добавить результат ответа'), ('change_answer_result', 'Может изменить результат ответа'), ('delete_answer_result', 'Может удалить результат ответа'), ('view_answer_result', 'Может просматривать результат ответа')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('score_scaled', models.PositiveIntegerField(default=0, verbose_name='Балл (%)')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_attempt_creators', related_query_name='test_attempt_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_attempt_editors', related_query_name='test_attempt_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', related_query_name='test_attempt', to='tests.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытка теста',
                'permissions': (('add_test_attempt', 'Может добавить попытку теста'), ('change_test_attempt', 'Может изменить попытку теста'), ('delete_test_attempt', 'Может удалить попытку теста'), ('view_test_attempt', 'Может просматривать попытку теста')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='questionresult',
            name='test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_results', related_query_name='question_result', to='bpms.testattempt', verbose_name='Попытка теста'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_scaled', models.PositiveIntegerField(default=0, verbose_name='Балл (%)')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_result_creators', related_query_name='test_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_result_editors', related_query_name='test_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_results', related_query_name='test_result', to='bpms.controlelement', verbose_name='Итог задачи')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_result', related_query_name='test_result', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты теста',
                'permissions': (('add_test_result', 'Может добавить результат теста'), ('change_test_result', 'Может изменить результат теста'), ('delete_test_result', 'Может удалить результат теста'), ('view_test_result', 'Может просматривать результат теста')),
                'default_permissions': (),
            },
        ),
    ]
