# Generated by Django 5.1 on 2025-06-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0020_questionresult_answerresult_testattempt_and_more'),
        ('tests', '0004_test_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='tests.test', verbose_name='Тест'),
        ),
    ]
