# Generated by Django 5.1 on 2025-06-26 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0021_task_test'),
        ('tests', '0004_test_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', related_query_name='task_template', to='tests.test', verbose_name='Тест'),
        ),
    ]
