# Generated by Django 5.1 on 2025-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0023_remove_testattempt_test_testattempt_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='plan_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
    ]
