# Generated by Django 5.1 on 2025-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0025_rename_question_attempt_answerresult_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Окончен'),
        ),
    ]
