# Generated by Django 5.1 on 2025-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0026_taskresult_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='finished',
        ),
        migrations.AddField(
            model_name='testresult',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Окончен'),
        ),
    ]
