# Generated by Django 5.1 on 2025-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0027_remove_taskresult_finished_testresult_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='question_sorting',
            field=models.TextField(default='[]', verbose_name='Сортировка вопросов'),
        ),
    ]
