# Generated by Django 5.1 on 2025-07-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0028_testattempt_question_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerresult',
            name='selected_answer',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
    ]
