# Generated by Django 5.1 on 2025-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0029_alter_answerresult_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
    ]
