# Generated by Django 5.1 on 2025-08-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0031_alter_answerresult_question_result'),
        ('events', '0004_alter_eventtemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_slots', related_query_name='event_slot', to='events.eventslot', verbose_name='Слот мероприятия'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_templates', related_query_name='event_template', to='events.eventtemplate', verbose_name='Мероприятие'),
        ),
    ]
