# Generated by Django 5.1 on 2025-08-19 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0032_task_event_slot_tasktemplate_event_template'),
        ('events', '0006_eventtemplate_term_type_eventtemplate_term_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_slots', related_query_name='event_slot', to='events.eventslot', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_templates', related_query_name='event_template', to='events.eventtemplate', verbose_name='Шаблон мероприятия'),
        ),
        migrations.CreateModel(
            name='EventSlotResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('finished', models.BooleanField(default=False, verbose_name='Окончен')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_slot_result_creators', related_query_name='event_slot_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_slot_result_editors', related_query_name='event_slot_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_slot_results', related_query_name='event_slot_result', to='bpms.controlelement', verbose_name='Итог задачи')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_slot_result', related_query_name='event_slot_result', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат мероприятия',
                'verbose_name_plural': 'Результаты мероприятия',
                'permissions': (('add_event_slot_result', 'Может добавить результат мероприятия'), ('change_event_slot_result', 'Может изменить результат мероприятия'), ('delete_event_slot_result', 'Может удалить результат мероприятия'), ('view_event_slot_result', 'Может просматривать результат мероприятия')),
                'default_permissions': (),
            },
        ),
    ]
