# Generated by Django 5.1 on 2025-08-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0033_alter_task_event_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventslotresult',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='eventslotresult',
            name='finished',
        ),
    ]
