# Generated by Django 5.1 on 2025-08-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0034_remove_eventslotresult_attempts_and_more'),
        ('events', '0009_alter_eventslot_event_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to='events.eventtemplate', verbose_name='Шаблон мероприятия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='events.eventslot', verbose_name='Мероприятие'),
        ),
    ]
