# Generated by Django 5.1 on 2025-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0035_task_event_template_alter_task_event_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slot_selection',
            field=models.BooleanField(default=False, verbose_name='Выбор слота'),
        ),
    ]
