# Generated by Django 5.1 on 2025-08-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0036_task_slot_selection'),
        ('events', '0011_alter_eventtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to='events.eventtemplate', verbose_name='Программа мероприятия'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_templates', related_query_name='event_template', to='events.eventtemplate', verbose_name='Программа мероприятия'),
        ),
    ]
