# Generated by Django 5.1 on 2025-08-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0037_alter_task_event_template_and_more'),
        ('events', '0011_alter_eventtemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='event_template',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slot_selection',
        ),
        migrations.AlterField(
            model_name='task',
            name='event_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='events.eventslot', verbose_name='Слот мероприятия'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_templates', related_query_name='event_template', to='events.eventtemplate', verbose_name='Мероприятие'),
        ),
    ]
