# Generated by Django 5.1 on 2025-09-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0038_remove_task_event_template_and_more'),
        ('events', '0015_remove_eventslot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='events.eventtemplate', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='task',
            name='slot_select',
            field=models.BooleanField(default=False, verbose_name='Выбор слота'),
        ),
    ]
