# Generated by Django 5.1 on 2025-09-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0040_eventresult_delete_eventslotresult'),
        ('events', '0015_remove_eventslot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='event_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', related_query_name='task_template', to='events.eventslot', verbose_name='Слот мероприятия'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='slot_select',
            field=models.BooleanField(default=False, verbose_name='Выбор слота'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', related_query_name='task_template', to='events.eventtemplate', verbose_name='Мероприятие'),
        ),
    ]
