# Generated by Django 5.1 on 2025-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0041_tasktemplate_event_slot_tasktemplate_slot_select_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slot_select',
            field=models.BooleanField(default=True, verbose_name='Выбор слота'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='slot_select',
            field=models.BooleanField(default=True, verbose_name='Выбор слота'),
        ),
    ]
