# Generated by Django 5.1 on 2025-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0042_alter_task_slot_select_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвердил участие'),
        ),
    ]
