# Generated by Django 5.1 on 2025-11-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0043_eventresult_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementcondition',
            name='logic_operator',
            field=models.CharField(blank=True, choices=[('and', 'И'), ('or', 'ИЛИ')], max_length=50, null=True, verbose_name='Логический оператор'),
        ),
    ]
