# Generated by Django 5.1 on 2025-11-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0044_controlelementcondition_logic_operator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlElementActivation',
        ),
    ]
