# Generated by Django 5.1 on 2025-11-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0045_delete_controlelementactivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlElementActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('control_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', related_query_name='activation', to='bpms.controlelement', verbose_name='Управляющий элемент')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_element_activations', related_query_name='control_element_activation', to='bpms.interaction', verbose_name='Взаимодействие')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', related_query_name='activation', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Срабатывание управляющего элемента',
                'verbose_name_plural': 'Срабатывания управляющих элементов',
                'permissions': (('add_control_element_activation', 'Может добавить срабатывание управляющего элемента'), ('change_control_element_activation', 'Может изменить срабатывание управляющего элемента'), ('delete_control_element_activation', 'Может удалить срабатывание управляющего элемента'), ('view_control_element_activation', 'Может просматривать срабатывание управляющего элемента')),
                'default_permissions': (),
            },
        ),
    ]
