# Generated by Django 5.1 on 2025-11-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0046_controlelementactivation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementactivation',
            name='task',
        ),
    ]
