# Generated by Django 5.1 on 2025-11-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0047_remove_controlelementactivation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('selected', 'Выбранное взаимодействие'), ('last', 'Последнее взаимодействие исполнителя'), ('new', 'Новое взаимодействие исполнителя')], max_length=50, null=True, verbose_name='Тип взаимодействия'),
        ),
    ]
