# Generated by Django 5.1 on 2025-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0048_tasktemplateassignment_interaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='interaction_frame',
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('current', 'Текущее взаимодействие с объектом'), ('new', 'Новое взаимодействие объекта')], max_length=50, null=True, verbose_name='Тип взаимодействия'),
        ),
    ]
