# Generated by Django 5.1 on 2025-11-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0049_remove_controlelementaction_interaction_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='interaction_frame',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('all', 'Все')], max_length=50, null=True, verbose_name='Рамки взаимодействия'),
        ),
    ]
