# Generated by Django 5.1 on 2025-11-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0050_remove_controlelementaction_interaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementevent',
            name='interaction_frame',
        ),
    ]
