# Generated by Django 5.1 on 2025-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0051_remove_controlelementevent_interaction_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementaction',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('последнее', 'Последнее')], max_length=50, null=True, verbose_name='Тип взаимодействия'),
        ),
    ]
