# Generated by Django 5.1 on 2025-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0052_controlelementaction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementaction',
            name='interaction_type',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('last', 'Последнее')], max_length=50, null=True, verbose_name='Тип взаимодействия'),
        ),
    ]
