# Generated by Django 5.1 on 2025-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0053_alter_controlelementaction_interaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='target_interaction',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('last', 'Последнее')], max_length=50, null=True, verbose_name='Целевое взаимодействие'),
        ),
    ]
