# Generated by Django 5.1 on 2025-11-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0054_remove_controlelementaction_interaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='target_interaction',
        ),
    ]
