# Generated by Django 5.1 on 2025-11-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0055_remove_controlelementaction_target_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementcondition',
            name='interaction_frame',
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='target_interaction',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('last', 'Последнее')], max_length=50, null=True, verbose_name='Целевое взаимодействие'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='target_task',
            field=models.CharField(blank=True, choices=[('current', 'Последняя задача в рамках текущего взаимодействия'), ('all', 'Последняя задача в рамках всех взаимодействий')], max_length=50, null=True, verbose_name='Целевая задача'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='target_task',
            field=models.CharField(blank=True, choices=[('current', 'Последняя задача в рамках текущего взаимодействия'), ('all', 'Последняя задача в рамках всех взаимодействий')], max_length=50, null=True, verbose_name='Целевая задача'),
        ),
    ]
