# Generated by Django 5.1 on 2025-11-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0056_remove_controlelementcondition_interaction_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='assignment_condition',
        ),
        migrations.RemoveField(
            model_name='controlelementaction',
            name='interaction_frame',
        ),
    ]
