# Generated by Django 5.1 on 2025-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0057_remove_controlelementaction_assignment_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplateassignment',
            name='assignment_condition',
        ),
        migrations.RemoveField(
            model_name='tasktemplateassignment',
            name='interaction_frame',
        ),
    ]
