# Generated by Django 5.1 on 2025-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0058_remove_tasktemplateassignment_assignment_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='last_executor_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер последнего исполнителя'),
        ),
    ]
