# Generated by Django 5.1 on 2025-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0059_alter_queue_last_executor_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='last_executor_item',
        ),
        migrations.AddField(
            model_name='queue',
            name='last_executor_idx',
            field=models.IntegerField(default=0, verbose_name='Индекс последнего исполнителя'),
        ),
    ]
