# Generated by Django 5.1 on 2025-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0060_remove_queue_last_executor_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelement',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Многократное срабатывание'),
        ),
    ]
