# Generated by Django 5.1 on 2025-11-28 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0061_controlelement_repeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerresult',
            options={'default_permissions': (), 'permissions': (('add_answer_result', 'Может добавить результат ответа'), ('change_answer_result', 'Может изменить результат ответа'), ('delete_answer_result', 'Может удалить результат ответа'), ('view_answer_result', 'Может просматривать результат ответа')), 'verbose_name': 'Результат ответа', 'verbose_name_plural': 'Результаты ответов'},
        ),
        migrations.AlterModelOptions(
            name='courseresult',
            options={'default_permissions': (), 'permissions': (('add_course_result', 'Может добавить результат курса'), ('change_course_result', 'Может изменить результат курса'), ('delete_course_result', 'Может удалить результат курса'), ('view_course_result', 'Может просматривать результат курса')), 'verbose_name': 'Результат курса', 'verbose_name_plural': 'Результаты курсов'},
        ),
        migrations.AlterModelOptions(
            name='materialresult',
            options={'default_permissions': (), 'permissions': (('add_material_result', 'Может добавить результат материала'), ('change_material_result', 'Может изменить результат материала'), ('delete_material_result', 'Может удалить результат материала'), ('view_material_result', 'Может просматривать результат материала')), 'verbose_name': 'Результат материала', 'verbose_name_plural': 'Результаты материалов'},
        ),
        migrations.AlterModelOptions(
            name='questionresult',
            options={'default_permissions': (), 'permissions': (('add_question_result', 'Может добавить результат вопроса'), ('change_question_result', 'Может изменить результат вопроса'), ('delete_question_result', 'Может удалить результат вопроса'), ('view_question_result', 'Может просматривать результат вопроса')), 'verbose_name': 'Результат вопроса', 'verbose_name_plural': 'Результаты вопросов'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'default_permissions': (), 'permissions': (('add_test_result', 'Может добавить результат теста'), ('change_test_result', 'Может изменить результат теста'), ('delete_test_result', 'Может удалить результат теста'), ('view_test_result', 'Может просматривать результат теста')), 'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.CreateModel(
            name='NewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_result_creators', related_query_name='new_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_result_editors', related_query_name='new_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_results', related_query_name='new_result', to='bpms.controlelement', verbose_name='Итог задачи')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_result', related_query_name='new_result', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат новости',
                'verbose_name_plural': 'Результаты новостей',
                'permissions': (('add_new_result', 'Может добавить результат новости'), ('change_new_result', 'Может изменить результат новости'), ('delete_new_result', 'Может удалить результат новости'), ('view_new_result', 'Может просматривать результат новости')),
                'default_permissions': (),
            },
        ),
    ]
