# Generated by Django 5.1 on 2025-11-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0062_alter_answerresult_options_and_more'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='task', to='news.new', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_templates', related_query_name='task_template', to='news.new', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('common_task', 'Обычная задача'), ('plan_implementation', 'Реализация плана'), ('news_reading', 'Чтение новостей'), ('material_review', 'Ознакомление с материалом'), ('test_taking', 'Прохождение теста'), ('course_study', 'Изучение курса'), ('event_participation', 'Участие в мероприятии')], max_length=50, null=True, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_type',
            field=models.CharField(blank=True, choices=[('common_task', 'Обычная задача'), ('plan_implementation', 'Реализация плана'), ('news_reading', 'Чтение новостей'), ('material_review', 'Ознакомление с материалом'), ('test_taking', 'Прохождение теста'), ('course_study', 'Изучение курса'), ('event_participation', 'Участие в мероприятии')], max_length=50, null=True, verbose_name='Тип задачи'),
        ),
    ]
