# Generated by Django 5.1 on 2025-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0063_task_new_tasktemplate_new_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementevent',
            name='period',
            field=models.CharField(blank=True, choices=[('client_created', 'Клиент создан'), ('account_created', 'Аккаунт создан'), ('task_created', 'Задача создана'), ('child_task_status_changed', 'Изменился статус дочерней задачи'), ('task_deadline', 'Истек срок задачи'), ('task_status_changed', 'Изменился статус задачи'), ('task_outcome_changed', 'Изменился итог задачи'), ('trigger_fired', 'Сработал триггер'), ('periodic_event', 'Периодическое событие')], max_length=50, null=True, verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='controlelementevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='controlelementevent',
            name='event_type',
            field=models.CharField(choices=[('client_created', 'Клиент создан'), ('account_created', 'Аккаунт создан'), ('task_created', 'Задача создана'), ('child_task_status_changed', 'Изменился статус дочерней задачи'), ('task_deadline', 'Истек срок задачи'), ('task_status_changed', 'Изменился статус задачи'), ('task_outcome_changed', 'Изменился итог задачи'), ('trigger_fired', 'Сработал триггер'), ('periodic_event', 'Периодическое событие')], max_length=50, verbose_name='Событие'),
        ),
    ]
