# Generated by Django 5.1 on 2025-12-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0064_controlelementevent_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementevent',
            name='period',
            field=models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=50, null=True, verbose_name='Событие'),
        ),
    ]
