# Generated by Django 5.1 on 2025-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0065_alter_controlelementevent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementevent',
            name='work_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время срабатывания'),
        ),
    ]
