# Generated by Django 5.1 on 2025-12-11 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0066_controlelementevent_work_time'),
        ('core', '0010_rename_agree_to_user_agreement_account_agree_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementaction',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_groups', related_query_name='target_group', to='core.accountsgroup', verbose_name='Целевая группа'),
        ),
        migrations.AlterField(
            model_name='controlelementaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('change_task_status', 'Изменить статус задачи'), ('change_task_outcome', 'Изменить итог задачи'), ('assign_task', 'Назначить задачу'), ('add_task_to_queue', 'Добавить задачу в очередь'), ('new_interaction', 'Новое взаимодействие'), ('add_to_group', 'Добавить исполнителя в группу'), ('remove_from_group', 'Удалить исполнителя из группы')], max_length=50, null=True, verbose_name='Действия'),
        ),
    ]
