# Generated by Django 5.1 on 2025-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0067_controlelementaction_target_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('change_task_status', 'Изменить статус задачи'), ('change_task_outcome', 'Изменить итог задачи'), ('assign_task', 'Назначить задачу'), ('add_task_to_queue', 'Добавить задачу в очередь'), ('new_interaction', 'Новое взаимодействие'), ('add_to_group', 'Добавить аккаунт взаимодействия в группу'), ('remove_from_group', 'Удалить аккаунт взаимодействия из группы')], max_length=50, null=True, verbose_name='Действия'),
        ),
    ]
