# Generated by Django 5.1 on 2025-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0068_alter_controlelementaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='self_assignment',
            field=models.BooleanField(default=False, verbose_name='Самоназначение'),
        ),
    ]
