# Generated by Django 5.1 on 2025-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0069_tasktemplate_self_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplateassignment',
            name='self_assignment',
            field=models.BooleanField(default=False, verbose_name='Самоназначение'),
        ),
    ]
