# Generated by Django 5.1 on 2025-12-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0071_task_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to='bpms.tasktemplateassignment'),
        ),
    ]
