# Generated by Django 5.1 on 2025-12-15 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0072_alter_task_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementcondition',
            name='days_worked_gte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано от (дней)'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='days_worked_lte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отработано до (дней)'),
        ),
    ]
