# Generated by Django 5.1 on 2025-12-15 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0073_controlelementcondition_days_worked_gte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked_gte', 'Стаж аккаунта взаимодействия более (дней)'), ('days_worked_lte', 'Стаж аккаунта взаимодействия менее (дней)')], max_length=50, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='days_worked_gte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стаж аккаунта взаимодействия более (дней)'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='days_worked_lte',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж аккаунта взаимодействия менее (дней)'),
        ),
    ]
