# Generated by Django 5.1 on 2025-12-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0074_alter_controlelementcondition_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked_gte', 'Минимальный стаж аккаунта взаимодействия (дней)'), ('days_worked_lte', 'Максимальный стаж аккаунта взаимодействия (дней)')], max_length=50, verbose_name='Условие'),
        ),
    ]
