# Generated by Django 5.1 on 2025-12-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0075_alter_controlelementcondition_condition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementcondition',
            name='days_worked_gte',
        ),
        migrations.RemoveField(
            model_name='controlelementcondition',
            name='days_worked_lte',
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='days_worked',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дни стажа'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='order_operators',
            field=models.CharField(blank=True, choices=[('gte', 'Больше или равно'), ('lte', 'Меньше или равн')], max_length=50, null=True, verbose_name='Оператор сравнения'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='comparison_operator',
            field=models.CharField(blank=True, choices=[('equal', 'Равно'), ('not_equal', 'Не равно')], max_length=50, null=True, verbose_name='Оператор сравнения'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked', 'Стаж аккаунта из взаимодействия')], max_length=50, verbose_name='Условие'),
        ),
    ]
