# Generated by Django 5.1 on 2025-12-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0076_remove_controlelementcondition_days_worked_gte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlelementcondition',
            old_name='order_operators',
            new_name='order_operator',
        ),
    ]
