# Generated by Django 5.1 on 2025-12-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0077_rename_order_operators_controlelementcondition_order_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetask',
            name='status',
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked', 'Стаж аккаунта взаимодействия')], max_length=50, verbose_name='Условие'),
        ),
    ]
