# Generated by Django 5.1 on 2025-12-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0078_remove_queuetask_status_and_more'),
        ('core', '0010_rename_agree_to_user_agreement_account_agree_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='interactions', related_query_name='interaction', to='core.category', verbose_name='Категории'),
        ),
    ]
