# Generated by Django 5.1 on 2025-12-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0079_interaction_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_analytics', 'Может просматривать аналитику'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
