# Generated by Django 5.1 on 2025-12-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0080_analytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': (), 'permissions': (('add_task', 'Может добавить задачу'), ('change_task', 'Может изменить задачу'), ('delete_task', 'Может удалить задачу'), ('view_task', 'Может просматривать задачу'), ('view_analytics', 'Может просматривать аналитику')), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
