# Generated by Django 5.1 on 2026-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0081_delete_analytics_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='target_task',
        ),
        migrations.RemoveField(
            model_name='controlelementcondition',
            name='target_task',
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='assign_interaction',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('last', 'Последнее')], max_length=50, null=True, verbose_name='Целевое взаимодействие'),
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='task_interaction',
            field=models.CharField(blank=True, choices=[('current', 'Текущее взаимодействие'), ('all', 'Последнее взаимодействие')], max_length=50, null=True, verbose_name='Целевое взаимодействие'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='task_interaction',
            field=models.CharField(blank=True, choices=[('current', 'Текущее взаимодействие'), ('all', 'Последнее взаимодействие')], max_length=50, null=True, verbose_name='Целевое взаимодействие'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('task_not_exists', 'Задача не назначалась'), ('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked', 'Стаж аккаунта взаимодействия')], max_length=50, verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='controlelementevent',
            name='event_type',
            field=models.CharField(choices=[('child_task_status_changed', 'Изменился статус дочерней задачи'), ('task_deadline', 'Истек срок задачи'), ('task_status_changed', 'Изменился статус задачи'), ('task_outcome_changed', 'Изменился итог задачи'), ('trigger_fired', 'Сработал триггер'), ('periodic_event', 'Периодическое событие')], max_length=50, verbose_name='Событие'),
        ),
    ]
