# Generated by Django 5.1 on 2026-01-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0082_remove_controlelementaction_target_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementaction',
            name='target_interaction',
        ),
    ]
