# Generated by Django 5.1 on 2026-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0083_remove_controlelementaction_target_interaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlelementaction',
            old_name='assign_interaction',
            new_name='target_interaction',
        ),
        migrations.RemoveField(
            model_name='controlelementaction',
            name='task_interaction',
        ),
        migrations.RemoveField(
            model_name='controlelementcondition',
            name='task_interaction',
        ),
        migrations.AddField(
            model_name='controlelementaction',
            name='target_task',
            field=models.CharField(blank=True, choices=[('current', 'Последняя задача в рамках текущего взаимодействия'), ('all', 'Последняя задача в рамках всех взаимодействий')], max_length=50, null=True, verbose_name='Целевая задача'),
        ),
        migrations.AddField(
            model_name='controlelementcondition',
            name='target_task',
            field=models.CharField(blank=True, choices=[('current', 'Последняя задача в рамках текущего взаимодействия'), ('all', 'Последняя задача в рамках всех взаимодействий')], max_length=50, null=True, verbose_name='Целевая задача'),
        ),
    ]
