# Generated by Django 5.1 on 2026-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0084_rename_assign_interaction_controlelementaction_target_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementcondition',
            name='target_interaction',
            field=models.CharField(blank=True, choices=[('current', 'Текущее'), ('last', 'Последнее')], max_length=50, null=True, verbose_name='Целевое взаимодействие'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='order_operator',
            field=models.CharField(blank=True, choices=[('gte', 'Больше или равно'), ('lte', 'Меньше или равно')], max_length=50, null=True, verbose_name='Оператор сравнения'),
        ),
    ]
