# Generated by Django 5.1 on 2026-01-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0085_controlelementcondition_target_interaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementcondition',
            name='target_interaction',
        ),
    ]
