# Generated by Django 5.1 on 2026-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0086_remove_controlelementcondition_target_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementaction',
            name='target_task',
            field=models.CharField(blank=True, choices=[('current', 'В рамках текущего взаимодействия'), ('all', 'В рамках всех взаимодействий')], max_length=50, null=True, verbose_name='Целевая задача'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='target_task',
            field=models.CharField(blank=True, choices=[('current', 'В рамках текущего взаимодействия'), ('all', 'В рамках всех взаимодействий')], max_length=50, null=True, verbose_name='Целевая задача'),
        ),
    ]
