# Generated by Django 5.1 on 2026-01-17 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0087_alter_controlelementaction_target_task_and_more'),
        ('core', '0013_rename_agree_legal_account_legal_agree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='public_plan_avatars/', verbose_name='Аватар')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, related_name='public_plans', related_query_name='public_plan', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_plan_creators', related_query_name='public_plan_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_plan_editors', related_query_name='public_plan_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_public_plans', related_query_name='task_template_public_plan', to='bpms.tasktemplate', verbose_name='Шаблон задачи')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задание',
                'permissions': (('add_public_plan', 'Может добавить задачу'), ('change_public__plan', 'Может изменить задачу'), ('delete_public__plan', 'Может удалить задачу'), ('view_public__plan', 'Может просматривать задачу')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PublicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='public_task_avatars/', verbose_name='Аватар')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, related_name='public_tasks', related_query_name='public_task', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_task_creators', related_query_name='public_task_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_task_editors', related_query_name='public_task_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_template_public_tasks', related_query_name='task_template_public_task', to='bpms.tasktemplate', verbose_name='Шаблон задачи')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задание',
                'permissions': (('add_public_task', 'Может добавить задачу'), ('change_public__task', 'Может изменить задачу'), ('delete_public__task', 'Может удалить задачу'), ('view_public__task', 'Может просматривать задачу')),
                'default_permissions': (),
            },
        ),
    ]
