# Generated by Django 5.1 on 2026-01-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0088_publicplan_publictask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicplan',
            options={'default_permissions': (), 'permissions': (('add_public_plan', 'Может добавить задачу'), ('change_public_plan', 'Может изменить задачу'), ('delete_public_plan', 'Может удалить задачу'), ('view_public_plan', 'Может просматривать задачу')), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задание'},
        ),
        migrations.AlterModelOptions(
            name='publictask',
            options={'default_permissions': (), 'permissions': (('add_public_task', 'Может добавить задачу'), ('change_public_task', 'Может изменить задачу'), ('delete_public_task', 'Может удалить задачу'), ('view_public_task', 'Может просматривать задачу')), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задание'},
        ),
    ]
