# Generated by Django 5.1 on 2026-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0089_alter_publicplan_options_alter_publictask_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicplan',
            options={'default_permissions': (), 'permissions': (('add_public_plan', 'Может добавить план'), ('change_public_plan', 'Может изменить план'), ('delete_public_plan', 'Может удалить план'), ('view_public_plan', 'Может просматривать план')), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задание'},
        ),
        migrations.AlterModelOptions(
            name='publictask',
            options={'default_permissions': (), 'permissions': (('add_public_task', 'Может добавить задание'), ('change_public_task', 'Может изменить задание'), ('delete_public_task', 'Может удалить задание'), ('view_public_task', 'Может просматривать задание')), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задание'},
        ),
    ]
