# Generated by Django 5.1 on 2026-01-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0091_alter_controlelementcondition_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementcondition',
            name='boolean_operator',
            field=models.BooleanField(default=False, verbose_name='Оператор сравнения'),
        ),
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('task_exists', 'Задача назначалась'), ('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked', 'Стаж аккаунта взаимодействия')], max_length=50, verbose_name='Условие'),
        ),
    ]
