# Generated by Django 5.1 on 2026-01-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0092_controlelementcondition_boolean_operator_and_more'),
        ('core', '0013_rename_agree_legal_account_legal_agree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlelementevent',
            name='event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to='core.accountsgroup', verbose_name='Группа события'),
        ),
    ]
