# Generated by Django 5.1 on 2026-01-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0093_controlelementevent_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlelementevent',
            name='event_group',
        ),
    ]
