# Generated by Django 5.1 on 2026-01-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0094_remove_controlelementevent_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementevent',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Аккаунт создан'), ('task_created', 'Задача создана'), ('child_task_status_changed', 'Изменился статус дочерней задачи'), ('task_deadline', 'Истек срок задачи'), ('task_status_changed', 'Изменился статус задачи'), ('task_outcome_changed', 'Изменился итог задачи'), ('trigger_fired', 'Сработал триггер'), ('periodic_event', 'Периодическое событие')], max_length=50, verbose_name='Событие'),
        ),
    ]
