# Generated by Django 5.1 on 2026-01-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0096_alter_controlelementevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlelementcondition',
            name='condition_type',
            field=models.CharField(choices=[('task_exists', 'Задача назначалась'), ('task_not_exists', 'Задача не назначалась'), ('child_tasks_status', 'Статус дочерних задач'), ('task_status', 'Статус задачи'), ('task_outcome', 'Итог задачи'), ('days_worked', 'Стаж аккаунта взаимодействия')], max_length=50, verbose_name='Условие'),
        ),
    ]
