# Generated by Django 5.1 on 2026-02-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0098_alter_controlelementcondition_condition_type'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('score_scaled', models.PositiveIntegerField(default=0, verbose_name='Балл (%)')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('plan_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('survey_question_sorting', models.TextField(default='[]', verbose_name='Сортировка вопросов')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_attempt_creators', related_query_name='survey_attempt_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_attempt_editors', related_query_name='survey_attempt_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Попытка опроса',
                'verbose_name_plural': 'Попытка опроса',
                'permissions': (('add_survey_attempt', 'Может добавить попытку опроса'), ('change_survey_attempt', 'Может изменить попытку опроса'), ('delete_survey_attempt', 'Может удалить попытку опроса'), ('view_survey_attempt', 'Может просматривать попытку опроса')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='assigned', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_question_result_creators', related_query_name='survey_question_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_question_result_editors', related_query_name='survey_question_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('survey_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_results', related_query_name='survey_question_result', to='bpms.surveyattempt', verbose_name='Попытка опроса')),
                ('survey_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_results', related_query_name='survey_question_result', to='surveys.surveyquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Результат вопроса опроса',
                'verbose_name_plural': 'Результаты вопросов опроса',
                'permissions': (('add_survey_question_result', 'Может добавить результат вопроса опроса'), ('change_survey_question_result', 'Может изменить результат вопроса опроса'), ('delete_survey_question_result', 'Может удалить результат вопроса опроса'), ('view_survey_question_result', 'Может просматривать результат вопроса опроса')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('selected_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Правильная позиция')),
                ('selected_text_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='Правильный ответ')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='assigned', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_answer_result_creators', related_query_name='survey_answer_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_answer_result_editors', related_query_name='survey_answer_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('survey_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer_results', related_query_name='survey_answer_result', to='surveys.surveyanswer', verbose_name='Ответ')),
                ('survey_question_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer_results', related_query_name='survey_answer_result', to='bpms.surveyquestionresult', verbose_name='Результат вопроса опроса')),
            ],
            options={
                'verbose_name': 'Результат ответа',
                'verbose_name_plural': 'Результаты ответов',
                'permissions': (('add_survey_answer_result', 'Может добавить результат ответа'), ('change_survey_answer_result', 'Может изменить результат ответа'), ('delete_survey_answer_result', 'Может удалить результат ответа'), ('view_survey_answer_result', 'Может просматривать результат ответа')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_scaled', models.PositiveIntegerField(default=0, verbose_name='Балл (%)')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='waiting', max_length=50, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('finished', models.BooleanField(default=False, verbose_name='Окончен')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_result_creators', related_query_name='survey_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_result_editors', related_query_name='survey_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_results', related_query_name='survey_result', to='bpms.controlelement', verbose_name='Итог задачи')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_result', related_query_name='survey_result', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Результат опроса',
                'verbose_name_plural': 'Результаты опросов',
                'permissions': (('add_survey_result', 'Может добавить результат опроса'), ('change_survey_result', 'Может изменить результат опроса'), ('delete_survey_result', 'Может удалить результат опроса'), ('view_survey_result', 'Может просматривать результат опроса')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='survey_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_attempts', related_query_name='survey_attempt', to='bpms.surveyresult', verbose_name='Тест'),
        ),
    ]
