# Generated by Django 5.1 on 2026-02-03 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0099_surveyattempt_surveyquestionresult_and_more'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В процессе'), ('completed', 'Выполнено'), ('failed', 'Провалено'), ('canceled', 'Отменено')], default='assigned', max_length=50, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_section_result_creators', related_query_name='survey_section_result_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_section_result_editors', related_query_name='survey_section_result_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('survey_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_section_results', related_query_name='survey_section_result', to='bpms.surveyattempt', verbose_name='Попытка опроса')),
                ('survey_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_section_results', related_query_name='survey_section_result', to='surveys.surveysection', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Результат секции опроса',
                'verbose_name_plural': 'Результаты секций опроса',
                'permissions': (('add_survey_section_result', 'Может добавить результат секции опроса'), ('change_survey_section_result', 'Может изменить результат секции опроса'), ('delete_survey_section_result', 'Может удалить результат секции опроса'), ('view_survey_section_result', 'Может просматривать результат секции опроса')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='surveyquestionresult',
            name='survey_section_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_results', related_query_name='survey_question_result', to='bpms.surveysectionresult', verbose_name='Результат секции опроса'),
        ),
    ]
