# Generated by Django 5.1 on 2026-02-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0100_surveysectionresult_and_more'),
        ('tests', '0009_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', related_query_name='survey', to='tests.test', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_templates', related_query_name='survey_template', to='tests.test', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('common_task', 'Обычная задача'), ('plan_implementation', 'Реализация плана'), ('news_reading', 'Чтение новостей'), ('material_review', 'Ознакомление с материалом'), ('test_taking', 'Прохождение теста'), ('survey_taking', 'Прохождение опроса'), ('course_study', 'Изучение курса'), ('event_participation', 'Участие в мероприятии')], max_length=50, null=True, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_type',
            field=models.CharField(blank=True, choices=[('common_task', 'Обычная задача'), ('plan_implementation', 'Реализация плана'), ('news_reading', 'Чтение новостей'), ('material_review', 'Ознакомление с материалом'), ('test_taking', 'Прохождение теста'), ('survey_taking', 'Прохождение опроса'), ('course_study', 'Изучение курса'), ('event_participation', 'Участие в мероприятии')], max_length=50, null=True, verbose_name='Тип задачи'),
        ),
    ]
