# Generated by Django 5.1 on 2025-05-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpms', '0014_remove_task_executor_outcome_and_more'),
        ('core', '0005_alter_accountsgroup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(blank=True, choices=[('common_topic', 'Обычный топик'), ('task_topic', 'Топик задачи'), ('queue_topic', 'Топик очереди')], max_length=20, null=True, verbose_name='Тип топика')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, related_name='topics', related_query_name='topic', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_creators', related_query_name='topic_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_editors', related_query_name='topic_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='bpms.queue', verbose_name='Очередь')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='bpms.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Топик',
                'verbose_name_plural': 'Топикы',
                'permissions': (('add_topic', 'Может добавить топик'), ('change_topic', 'Может изменить топик'), ('delete_topic', 'Может удалить топик'), ('view_topic', 'Может просматривать топик')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', related_query_name='child_message', to='comments.comment', verbose_name='Родительское сообщение')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_senders', related_query_name='topic_sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='comments.topic', verbose_name='Топик')),
            ],
            options={
                'verbose_name': 'Сообщение топика',
                'verbose_name_plural': 'Сообщения топика',
                'permissions': (('add_message', 'Может добавить сообщение'), ('change_message', 'Может изменить сообщение'), ('delete_message', 'Может удалить сообщение'), ('view_message', 'Может просматривать сообщение')),
                'default_permissions': (),
            },
        ),
    ]
