# Generated by Django 5.1 on 2025-05-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'default_permissions': (), 'permissions': (('add_topic', 'Может добавить топик'), ('change_topic', 'Может изменить топик'), ('delete_topic', 'Может удалить топик'), ('view_topic', 'Может просматривать топик')), 'verbose_name': 'Топик', 'verbose_name_plural': 'Топики'},
        ),
    ]
