# Generated by Django 5.1 on 2026-01-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpms', '0096_alter_controlelementevent_event_type'),
        ('comments', '0002_alter_topic_options'),
        ('courses', '0005_remove_course_self_assignment'),
        ('events', '0017_remove_eventslot_self_assignment'),
        ('materials', '0003_remove_material_self_assignment'),
        ('news', '0004_remove_new_self_assignment'),
        ('tests', '0007_remove_test_self_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='topic',
            name='event_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='events.eventslot', verbose_name='Слот мероприятия'),
        ),
        migrations.AddField(
            model_name='topic',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='events.eventtemplate', verbose_name='Шаблон мероприятия'),
        ),
        migrations.AddField(
            model_name='topic',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='materials.material', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='topic',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='news.new', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='topic',
            name='public_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='bpms.publicplan', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='topic',
            name='public_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='bpms.publictask', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='topic',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', related_query_name='topic', to='tests.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(blank=True, choices=[('common_topic', 'Обычный топик'), ('task_topic', 'Топик задачи'), ('queue_topic', 'Топик очереди'), ('public_plan_topic', 'Топик плана'), ('public_task_topic', 'Топик задания'), ('new_topic', 'Топик новости'), ('material_topic', 'Топик материала'), ('course_topic', 'Топик курса'), ('test_topic', 'Топик теста'), ('event_template_topic', 'Топик мероприятия'), ('event_slot_topic', 'Топик слота мероприятия')], max_length=20, null=True, verbose_name='Тип топика'),
        ),
    ]
