# Generated by Django 5.1 on 2026-02-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_topic_course_topic_event_slot_topic_event_template_and_more'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', related_query_name='survey', to='surveys.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(blank=True, choices=[('common_topic', 'Обычный топик'), ('task_topic', 'Топик задачи'), ('queue_topic', 'Топик очереди'), ('public_plan_topic', 'Топик плана'), ('public_task_topic', 'Топик задания'), ('new_topic', 'Топик новости'), ('material_topic', 'Топик материала'), ('course_topic', 'Топик курса'), ('test_topic', 'Топик теста'), ('survey_topic', 'Топик опроса'), ('event_template_topic', 'Топик мероприятия'), ('event_slot_topic', 'Топик слота мероприятия')], max_length=20, null=True, verbose_name='Тип топика'),
        ),
    ]
