"""
Django settings for light project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")
load_dotenv(BASE_DIR.parent / "deploy" / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-+vyhvpv-nbk21^vn^%c_6)mk)c23^-k)x)3&hv6mdm)olrh#55'
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-+vyhvpv-nbk21^vn^%c_6)mk)c23^-k)x)3&hv6mdm)olrh#55'
)


# RECAPTCHA_SECRET_KEY = "6Lcd_j8sAAAAAGaG05kocmPUM_DpIcMtGOlfpZjO"
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.getenv('DJANGO_DEBUG', '0') == '1'

# Разрешенные хосты.
# ALLOWED_HOSTS = [
    # Любой.
#   '*'
# ]
# Любые источники запросов.
# CORS_ORIGIN_ALLOW_ALL = True

ALLOWED_HOSTS = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    '*'
).split(',')


# CORS (Vue dev + nginx)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",      # Vue dev
    "http://127.0.0.1:5173",      # Vue dev alt
    "http://localhost",           # nginx
    "http://127.0.0.1",           # runserver
]


# CSRF (НЕ мешает JWT, но нужен Django admin)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://localhost:5173",
    "http://127.0.0.1",
    "http://127.0.0.1:5173",
]


# HTTPS behind nginx (на будущее)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Разрешение на фреймы для пакетов.
X_FRAME_OPTIONS = 'ALLOWALL'

# Application definition

INSTALLED_APPS = [
    # Для веб-сокетов.
    #'daphne',
    'channels',
    'channels_redis',
    # Стандартные.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # АПИ.
    'rest_framework',
    'rest_framework_simplejwt',
    # Разрешения запросов.
    'corsheaders',
    # Фильтры.
    'django_filters',
    # Объектные права.
    'guardian',
    # Проверка адресов.
    'django_extensions',
    # Подключаем периодические задачи.
    'django_apscheduler',
    # Приложения.
    'core.apps.CoreConfig',
    'bpms.apps.BpmsConfig',
    'chats.apps.ChatsConfig',
    'comments.apps.CommentsConfig',
    'files.apps.FilesConfig',
    'news.apps.NewsConfig',
    'materials.apps.MaterialsConfig',
    'courses.apps.CoursesConfig',
    'tests.apps.TestsConfig',
    'events.apps.EventsConfig',
    'notifications.apps.NotificationsConfig',
]

MIDDLEWARE = [
    # Разрешения запросов.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'light.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#Асинхронный обработкик.
ASGI_APPLICATION = 'light.asgi.application'
#Синхронный обработкик.
WSGI_APPLICATION = 'light.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'postgres'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'm@y!C00l'),
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Локализация.
# Устанавливает основной язык проекта на русский ('ru').
LANGUAGE_CODE = 'ru'
# Устанавливает временную зону на 'Europe/Moscow'.
TIME_ZONE = 'Europe/Moscow'
# Включает поддержку интернационализации (I18N).
USE_I18N = True
# Включает локализацию (L10N), то есть форматирование данных в соответствии с культурными нормами.
USE_L10N = True
# Включает поддержку временных зон, сохраняя время в UTC и преобразовывая его в локальное.
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Настрока статических файлов.
# Путь к статическим файлам.
# ВАЖНО! Указаываем передний "/",
# чтобы поиск был в корне проекта,
# а не относительно текущего пути.
STATIC_URL = '/static/'
# Список директорий, где будут статические файлы,
# кроме директорий 'static' внутри приложений.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Директория для развертываения в продакшене,
# до продакшана смысла использовать нет.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Настройка медиафайлов:
# все по аналогии со статическими.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройка бэкэнда аутентификации.
AUTHENTICATION_BACKENDS = (
   # Стандартный бэкенд.
   'django.contrib.auth.backends.ModelBackend',
   # Для расширенных прав доступа.
   'guardian.backends.ObjectPermissionBackend',
)

# нестандартная модель юзера и групп
AUTH_USER_MODEL = 'core.Account'
AUTH_GROUP_MODEL = 'core.AccountsGroup'
# Расширенные права.
GUARDIAN_GROUP_OBJ_PERMS_MODEL = 'core.AccountsGroupObjectPermission'
GUARDIAN_USER_OBJ_PERMS_MODEL = 'core.AccountObjectPermission'
ANONYMOUS_USER_ID = -1

# Хранение сессий в БД.
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True

# Настройки Simple JWT для аутентификации с использованием JSON Web Token

SIMPLE_JWT = {
    # Время жизни доступа (access token) в формате timedelta. По умолчанию 5 минут.
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),

    # Время жизни обновления (refresh token) в формате timedelta. По умолчанию 1 день.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # Использовать ли черный список для токенов.
    # Если True, это означает, что токены могут быть отозваны.
    'BLACKLIST_AFTER_ROTATION': True,

    # Отключение функции проверки для всех обновлений токенов.
    # Если True, это отключает проверки обновления токена.
    'UPDATE_LAST_LOGIN': False,

    # Алгоритм для подписи токенов. Обычно используется 'HS256'.
    'ALGORITHM': 'HS256',

    # Имя поля в запросе для отправки токена доступа.
    'AUTH_HEADER_TYPES': ('Bearer',),

    # Путь к классу для настройки черного списка токенов.
    # Если вам не нужен черный список, вы можете оставить это значение по умолчанию.
    'TOKEN_BLACKLIST': 'rest_framework_simplejwt.token_blacklist.models.BlacklistedToken',

    # Настройки для работы с черным списком.
    'TOKEN_BLACKLIST_OPTIONS': {
        'USER_MODEL': 'auth.User',  # Модель пользователя, используемая для хранения данных пользователя.
    },

    # Настройки для создания токена.
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',

    # Настройки для получения обновленного токена.
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',

    # Использовать ли аутентификацию по токену, основанную на IP-адресе пользователя.
    'AUTHORIZATION': True,
}


# Настройки АПИ.
REST_FRAMEWORK = {
    # Классы аутентификации по умолчанию.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Аутентификация на основе сессий Django
        'rest_framework.authentication.BasicAuthentication',  # Базовая аутентификация (логин/пароль в заголовке HTTP)
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Аутентификация с использованием JWT
        #'rest_framework.authentication.TokenAuthentication',  # Аутентификация с использованием токенов
        #'rest_framework_api_key.authentication.APIKeyAuthentication',  # Аутентификация с использованием API-ключей
    ],

    # Классы разрешений по умолчанию.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Доступ только для аутентифицированных пользователей
        #'rest_framework_api_key.permissions.HasAPIKey',  # Доступ тех у кого есть ключ
        #'rest_framework.permissions.AllowAny',  # Доступ открыт для всех
        #'rest_framework.permissions.IsAdminUser',  # Доступ только для администраторов (is_staff)
        #'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Чтение для всех, изменения только для аутентифицированных
        #'rest_framework.permissions.DjangoModelPermissions',  # Проверяет разрешения на уровне моделей Django
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',  # Комбинация разрешений моделей и открытого доступа для чтения
    ],

    # Параметры пагинации.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # Пагинация по номеру страницы
    'PAGE_SIZE': 999999,  # Количество объектов на странице по умолчанию

    # Классы фильтрации по умолчанию.
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # Фильтрация на основе Django Filter
        'rest_framework.filters.SearchFilter',  # Фильтрация на основе строк поиска
        'rest_framework.filters.OrderingFilter',  # Сортировка объектов в ответе
    ],

    # Классы рендеринга (вывода данных) по умолчанию.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Рендеринг данных в формате JSON
        # Можно добавить другие рендереры, например, BrowsableAPIRenderer, XMLRenderer, YAMLRenderer, и т.д.
    ],

    # Классы парсинга (входящих данных) по умолчанию.
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',  # Парсинг входящих данных в формате JSON
        'rest_framework.parsers.FormParser',  # Парсинг форм, например, application/x-www-form-urlencoded
        'rest_framework.parsers.MultiPartParser',  # Парсинг multipart/form-data для загрузки файлов
        # Вы можете добавить другие парсеры, такие как FormParser, MultiPartParser, или XMLParser, если ваш API должен обрабатывать разные типы данных.
    ],

    # Обработчик исключений (ошибок) по умолчанию.
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',  # Стандартный обработчик исключений DRF

    # Настройка режима тестирования.
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',  # Использовать JSON по умолчанию при тестировании API
    # Удобно, чтобы не нужно было задавать формат данных в каждом тесте вручную.

    # Версионирование API.
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',  # Версионирование по URL (например, /v1/resource)
    # Можно использовать другие методы версионирования, такие как по HTTP-заголовкам или по параметрам запросов.
}

# Настройки почты.
# Эмейл бекэнд.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Отправляет письмо.
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Печатает письмо в консоли.
#EMAIL_HOST = 'smtp.ethereal.email'  # SMTP-сервер smtp.ethereal.email.
EMAIL_HOST = 'smtp.yandex.ru'  # SMTP-сервер smtp.yandex.ru.
EMAIL_PORT = 465  # Порт SMTP-сервера (обычно 587 для TLS или 465 для SSL).
EMAIL_USE_TLS = False  # Использовать ли TLS (для обеспечения безопасности). Для сервера smtp.ethereal.email и дургих.
EMAIL_USE_SSL = True  # Использовать ли SSL (для обеспечения безопасности). Для сервера smtp.yandex.ru и других.
#EMAIL_HOST_USER = 'diego.aufderhar37@ethereal.email'  # Ваш адрес электронной почты от smtp.ethereal.email.
#EMAIL_HOST_PASSWORD = 'yHRVdXG8c7kBeK2aD6'  # Пароль от вашего адреса электронной почты от smtp.ethereal.email.
#EMAIL_HOST_USER = 's.klimeshov.home@yandex.ru'  # Ваш адрес электронной почты от smtp.yandex.ru.
#EMAIL_HOST_PASSWORD = 'dfuavqrsxrukjucf'  # Пароль от вашего адреса электронной почты от smtp.yandex.ru.
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
#DEFAULT_FROM_EMAIL = "diego.aufderhar37@ethereal.email" # Адрес отправителя.
#DEFAULT_FROM_EMAIL = "s.klimeshov.home@yandex.ru" # Адрес отправителя.
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Логирование.
LOGGING = {
    # Версия конфигурации логирования. 1 — это единственное допустимое значение.
    'version': 1,

    # Если False, логгеры, установленные до загрузки этой конфигурации, не отключаются.
    'disable_existing_loggers': False,

    # Определение форматов сообщений лога.
    'formatters': {
        # Определение форматера с именем 'verbose'.
        'verbose': {
            # Указание формата сообщения.
            'format': '{levelname} {asctime} {module} {message}',
            # Стиль форматирования, использующий '{}'
            'style': '{',
        },
    },

    # Определение обработчиков сообщений лога.
    'handlers': {
        # Определение обработчика с именем 'file'.
        'file': {
            # Минимальный уровень логирования.
            'level': 'DEBUG',
            # Класс обработчика, записывающего сообщения в файл.
            'class': 'logging.handlers.TimedRotatingFileHandler',
            # Путь к файлу логов.
            'filename': 'debug.log',
            # Ротация раз в сутки.
            'when': 'midnight',
            # Интервал ротации (1 день).
            'interval': 1,
            # Хранить логи за последнюю неделю.
            'backupCount': 7,
            # Используемый форматер.
            'formatter': 'verbose',
            # Используемая кодировка.
            'encoding': 'utf-8',
            # Гарантируем, что ротация идёт по UTC-времени.
            'utc': True,
            # Откладывает открытие файла до первой записи
            'delay': True,
        },
        # Определение обработчика с именем 'console'.
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',  # Этот класс выводит сообщения в консоль.
            'formatter': 'verbose',
        },
    },

    # Определение логгеров.
    'loggers': {
        # Настройка логгера с именем 'project'.
        'project': {
            # Обработчики, которые будут использоваться этим логгером.
            'handlers': ['file', 'console'],
            # Минимальный уровень логирования для этого логгера.
            'level': 'DEBUG' if DEBUG else 'INFO',
            # Будет ли логгер передавать сообщения вышестоящим логгерам.
            'propagate': True,
        },
        # Настройка логгера для отлавливания ошибок Django запросов.
        'django.request': {
            # Обработчики, которые будут использоваться этим логгером.
            'handlers': ['file', 'console'],
            # Уровень логирования
            'level': 'ERROR',
            # Не передавать сообщения вышестоящим логгерам.
            'propagate': False,
        },
        # Настройка логгера для отлавливания ошибок безопасности Django.
        'django.security': {
            # Обработчики, которые будут использоваться этим логгером
            'handlers': ['file', 'console'],
            # Уровень логирования
            'level': 'ERROR',
            # Не передавать сообщения вышестоящим логгерам.
            'propagate': False,
        },
    },
}

# Установка и настройка Redis для использования с Channels.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [
                (
                    os.getenv('REDIS_HOST', '127.0.0.1'),
                    int(os.getenv('REDIS_PORT', 6379))
                )
            ],
        },
    },
}

