# Generated by Django 5.1 on 2025-11-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_groupgenerator_added_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='new_avatars/', verbose_name='Аватар')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='news', related_query_name='news', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_creators', related_query_name='new_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_editors', related_query_name='new_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новостьы',
                'permissions': (('add_new', 'Может добавить новость'), ('change_new', 'Может изменить новость'), ('delete_new', 'Может удалить новость'), ('view_new', 'Может просматривать новость')),
                'default_permissions': (),
            },
        ),
    ]
