# Generated by Django 5.1 on 2025-11-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'default_permissions': (), 'permissions': (('add_new', 'Может добавить новость'), ('change_new', 'Может изменить новость'), ('delete_new', 'Может удалить новость'), ('view_new', 'Может просматривать новость')), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
