# Generated by Django 5.1 on 2025-12-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='self_assignment',
            field=models.BooleanField(default=False, verbose_name='Самоназначение'),
        ),
    ]
