# Generated by Django 5.1 on 2025-12-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_self_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='self_assignment',
        ),
    ]
