# Generated by Django 5.1 on 2025-06-06 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_accountsgroup_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='course_avatars/', verbose_name='Аватар')),
                ('type', models.CharField(choices=[('ispring', 'Ispring'), ('articulate', 'Articulate'), ('scroll', 'Scroll')], default='', max_length=255, verbose_name='Тип')),
                ('zip_file', models.FileField(upload_to='scorm_packages/', verbose_name='Zip-файл')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='courses', related_query_name='courses', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_creators', related_query_name='course_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_editors', related_query_name='course_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'permissions': (('add_course', 'Может добавить курс'), ('change_course', 'Может изменить курс'), ('delete_course', 'Может удалить курс'), ('view_course', 'Может просматривать курс')),
                'default_permissions': (),
            },
        ),
    ]
