# Generated by Django 5.1 on 2025-06-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='course',
            name='constructor_type',
            field=models.CharField(blank=True, choices=[('ispring', 'Ispring'), ('articulate', 'Articulate'), ('scroll', 'Scroll')], max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='course',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='scorm_packages/', verbose_name='Файл'),
        ),
    ]
