# Generated by Django 5.1 on 2025-06-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_type_remove_course_zip_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'default_permissions': (), 'permissions': (('add_course', 'Может добавить курс'), ('change_course', 'Может изменить курс'), ('delete_course', 'Может удалить курс'), ('view_course', 'Может просматривать курс')), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
