# Generated by Django 5.1 on 2026-02-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_remove_groupgenerator_autoupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='survey_avatars/', verbose_name='Аватар')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('passing_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Проходной балл')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на выполнение (минут)')),
                ('attempts', models.PositiveIntegerField(blank=True, null=True, verbose_name='Попытки')),
                ('random_sections', models.BooleanField(default=True, verbose_name='Случайный порядок секций')),
                ('random_questions', models.BooleanField(default=True, verbose_name='Случайный порядок вопросов')),
                ('random_answers', models.BooleanField(default=True, verbose_name='Случайный порядок ответов')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='surveys', related_query_name='survey', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_creators', related_query_name='survey_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_editors', related_query_name='survey_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'permissions': (('add_survey', 'Может добавить опрос'), ('change_survey', 'Может изменить опрос'), ('delete_survey', 'Может удалить опрос'), ('view_survey', 'Может просматривать опрос')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_selection', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('sorting', 'Сортировка'), ('text_input', 'Текстовый ввод')], default='', max_length=255, verbose_name='Тип вопроса')),
                ('manual', models.TextField(verbose_name='Инструкция')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='survey_questions_picture/', verbose_name='Картинка вопроса')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='survey_questions', related_query_name='survey_question', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_question_creators', related_query_name='survey_question_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_question_editors', related_query_name='survey_question_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'permissions': (('add_survey_question', 'Может добавить вопрос'), ('change_survey_question', 'Может изменить вопрос'), ('delete_survey_question', 'Может удалить вопрос'), ('view_survey_question', 'Может просматривать вопрос')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(db_index=True, verbose_name='Позиция в списке')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='survey_answer_picture/', verbose_name='Картинка ответа')),
                ('score', models.IntegerField(default=0, verbose_name='Балл')),
                ('correct_answer', models.BooleanField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('correct_item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Правильная позиция')),
                ('correct_text_input', models.CharField(blank=True, max_length=255, null=True, verbose_name='Правильный ответ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_answer_creators', related_query_name='survey_answer_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_answer_editors', related_query_name='survey_answer_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', related_query_name='survey_answer', to='surveys.surveyquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'permissions': (('add_survey_answer', 'Может добавить ответ'), ('change_survey_answer', 'Может изменить ответ'), ('delete_survey_answer', 'Может удалить ответ'), ('view_survey_answer', 'Может просматривать ответ')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(verbose_name='Пункт')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_section_creators', related_query_name='survey_section_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_section_editors', related_query_name='survey_section_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_sections', related_query_name='survey_section', to='surveys.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Раздел опроса',
                'verbose_name_plural': 'Разделы опроса',
                'permissions': (('add_survey_section', 'Может добавить раздел опроса'), ('change_survey_section', 'Может изменить раздел опроса'), ('delete_survey_section', 'Может удалить раздел опроса'), ('view_survey_section', 'Может просматривать раздел опроса')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SurveySectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.PositiveIntegerField(verbose_name='Пункт')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_section_question_creators', related_query_name='survey_section_question_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_section_question_editors', related_query_name='survey_section_question_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('survey_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_section_questions', related_query_name='survey_section_question', to='surveys.surveyquestion', verbose_name='Вопрос')),
                ('survey_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_section_questions', related_query_name='survey_section_question', to='surveys.surveysection', verbose_name='Раздел опроса')),
            ],
            options={
                'verbose_name': 'Вопрос раздела опроса',
                'verbose_name_plural': 'Вопросы раздела опроса',
                'permissions': (('add_survey_section_question', 'Может добавить вопрос раздела опроса'), ('change_survey_section_question', 'Может изменить вопрос раздела опроса'), ('delete_survey_section_question', 'Может удалить вопрос раздела опроса'), ('view_survey_section_question', 'Может просматривать вопрос раздела опроса')),
                'default_permissions': (),
            },
        ),
    ]
