# Generated by Django 5.1 on 2025-12-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='self_assignment',
            field=models.BooleanField(default=False, verbose_name='Самоназначение'),
        ),
    ]
