# Generated by Django 5.1 on 2025-12-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_self_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='self_assignment',
        ),
    ]
