# Generated by Django 5.1 on 2025-03-22 14:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mdm_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MDM ID аккаунта')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts_avatar/', verbose_name='Аватар')),
                ('self_registration', models.BooleanField(default=False, verbose_name='Самостоятельная регистрация')),
                ('agree_to_privacy_policy', models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности')),
                ('agree_to_data_processing', models.BooleanField(default=False, verbose_name='Согласие с политикой в области обработки персональных данных')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Подтверждение электронной почты')),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Отчество')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_creators', related_query_name='account_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_editors', related_query_name='account_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'permissions': (('add_account', 'Может добавить аккаунт'), ('change_account', 'Может изменить аккаунт'), ('delete_account', 'Может удалить аккаунт'), ('view_account', 'Может просматривать аккаунт'), ('change_self_account', 'Может изменить свой аккаунт')),
                'default_permissions': (),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_object_permissions_creators', related_query_name='account_object_permissions_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Права сотрудника на объект',
                'verbose_name_plural': 'Права сотрудника на объекты',
                'permissions': (('add_account_object_permission', 'Может добавить права сотрудника на объект'), ('change_account_object_permission', 'Может изменить права сотрудника на объект'), ('delete_account_object_permission', 'Может удалить права сотрудника на объект'), ('view_account_object_permission', 'Может просматривать права сотрудника на объект')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountsGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(max_length=255, verbose_name='object ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_group_object_permissions_creators', related_query_name='accounts_group_object_permissions_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Права группы на объект',
                'verbose_name_plural': 'Права группы на объекты',
                'permissions': (('add_accounts_group_object_permission', 'Может добавить права группы на объект'), ('change_accounts_group_object_permission', 'Может изменить права группы на объект'), ('delete_accounts_group_object_permission', 'Может удалить права группы на объект'), ('view_accounts_group_object_permission', 'Может просматривать права группы на объект')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_creators', related_query_name='categories_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_editors', related_query_name='category_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', related_query_name='category', to='core.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'permissions': (('add_category', 'Может добавить категорию'), ('change_category', 'Может изменить категорию'), ('delete_category', 'Может удалить категорию'), ('view_category', 'Может просматривать категорию')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountsGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('type', models.CharField(choices=[('custom', 'Пользовательская'), ('system', 'Системная'), ('organization', 'Организация'), ('subdivision', 'Подразделение'), ('position', 'Должность'), ('task_co_executors', 'Соисполнители задачи'), ('task_controllers', 'Контролеры задачи'), ('task_observers', 'Наблюдатели задачи'), ('assignment', 'Назначение'), ('excel_import', 'Импорт из Excel'), ('api_import', 'Импорт по API'), ('event_participants', 'Участники мероприятия'), ('event_responsible', 'Ответственные мероприятия')], default='custom', max_length=255, verbose_name='Тип')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_creators', related_query_name='group_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_editors', related_query_name='group_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('categories', models.ManyToManyField(blank=True, related_name='groups', related_query_name='group', to='core.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'permissions': (('add_accounts_group', 'Может добавить группу'), ('change_accounts_group', 'Может изменить группу'), ('delete_accounts_group', 'Может удалить группу'), ('view_accounts_group', 'Может просматривать группу')),
                'default_permissions': (),
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdm_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MDM ID аккаунта')),
                ('client_type', models.CharField(blank=True, choices=[('internal', 'Внутренний'), ('external', 'Внешний')], max_length=8, null=True, verbose_name='Тип клиента')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('has_account', models.BooleanField(default=False, verbose_name='Имеет аккаунт')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', related_query_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт клиента')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_creators', related_query_name='client_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_editors', related_query_name='client_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'permissions': (('add_client', 'Может добавить клиента'), ('change_client', 'Может изменить клиента'), ('delete_client', 'Может удалить клиента'), ('view_client', 'Может просматривать клиента')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked_gte', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано от (дней)')),
                ('days_worked_lte', models.IntegerField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано до (дней)')),
                ('autoupdate', models.BooleanField(default=False, verbose_name='Автообновление')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('added_groups', models.ManyToManyField(blank=True, related_name='added_generators_groups', related_query_name='added_generators_group', to='core.accountsgroup', verbose_name='Добавляемые группы')),
                ('added_users', models.ManyToManyField(blank=True, related_name='added_generators_users', related_query_name='added_generators_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавляемые сотрудники')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_generators_creators', related_query_name='group_generators_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_generator_editors', related_query_name='group_generator_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('excluded_groups', models.ManyToManyField(blank=True, related_name='excluded_generators_groups', related_query_name='excluded_generators_group', to='core.accountsgroup', verbose_name='Исключаемые группы')),
                ('excluded_users', models.ManyToManyField(blank=True, related_name='excluded_generators_users', related_query_name='excluded_generators_user', to=settings.AUTH_USER_MODEL, verbose_name='Исключаемые сотрудники')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generator_group', related_query_name='generator_group', to='core.accountsgroup', verbose_name='Группа прав')),
            ],
            options={
                'verbose_name': 'Генератор групп',
                'verbose_name_plural': 'Генераторы групп',
                'permissions': (('add_group_generator', 'Может добавить генератор групп'), ('change_group_generator', 'Может изменить генератор групп'), ('delete_group_generator', 'Может удалить генератор групп'), ('view_group_generator', 'Может просматривать генератор групп')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdm_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MDM ID организации')),
                ('legal_name', models.CharField(db_index=True, max_length=255, verbose_name='Юридическое название')),
                ('tin', models.CharField(max_length=32, verbose_name='ИНН организации')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_creators', related_query_name='organizations_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_editors', related_query_name='organization_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', related_query_name='organization', to='core.accountsgroup', verbose_name='Группа прав')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'permissions': (('add_organization', 'Может добавить организацию'), ('change_organization', 'Может изменить организацию'), ('delete_organization', 'Может удалить организацию'), ('view_organization', 'Может просматривать организацию')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdm_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MDM ID должности')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_creators', related_query_name='positions_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_editors', related_query_name='position_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position', related_query_name='position', to='core.accountsgroup', verbose_name='Группа прав')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'permissions': (('add_position', 'Может добавить должность'), ('change_position', 'Может изменить должность'), ('delete_position', 'Может удалить должность'), ('view_position', 'Может просматривать должность')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер')], default='custom', max_length=255, verbose_name='Тип')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', related_query_name='placements', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements_creators', related_query_name='placements_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_editors', related_query_name='placement_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', related_query_name='placements', to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Назначение на должность',
                'verbose_name_plural': 'Назначение на должности',
                'permissions': (('add_placement', 'Может добавить назначение на должность'), ('change_placement', 'Может изменить назначение на должность'), ('delete_placement', 'Может удалить назначение на должность'), ('view_placement', 'Может просматривать назначение на должность')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdm_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MDM ID подразделения')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions_creators', related_query_name='subdivisions_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivision_editors', related_query_name='subdivision_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdivision', related_query_name='subdivision', to='core.accountsgroup', verbose_name='Группа прав')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', related_query_name='subdivision', to='core.organization', verbose_name='Организация')),
                ('parent_subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', related_query_name='subdivision', to='core.subdivision', verbose_name='Главное подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'permissions': (('add_subdivision', 'Может добавить подразделение'), ('change_subdivision', 'Может изменить подразделение'), ('delete_subdivision', 'Может удалить подразделение'), ('view_subdivision', 'Может просматривать подразделение')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='position',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', related_query_name='position', to='core.subdivision', verbose_name='Подразделение'),
        ),
    ]
