# Generated by Django 5.1 on 2025-03-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='has_account',
        ),
    ]
