# Generated by Django 5.1 on 2025-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_client_type_remove_client_has_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='account_avatars/', verbose_name='Аватар'),
        ),
    ]
