# Generated by Django 5.1 on 2025-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsgroup',
            name='type',
            field=models.CharField(choices=[('custom', 'Пользовательская'), ('system', 'Системная'), ('organization', 'Организация'), ('subdivision', 'Подразделение'), ('position', 'Должность'), ('task_executors', 'Исполнители задачи'), ('task_controllers', 'Контролеры задачи'), ('task_observers', 'Наблюдатели задачи'), ('assignment', 'Назначение'), ('excel_import', 'Импорт из Excel'), ('api_import', 'Импорт по API'), ('event_participants', 'Участники мероприятия'), ('event_responsible', 'Ответственные мероприятия')], default='custom', max_length=255, verbose_name='Тип'),
        ),
    ]
