# Generated by Django 5.1 on 2025-07-18 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_accountsgroup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgenerator',
            name='added_groups',
            field=models.ManyToManyField(blank=True, related_name='added_group_generator_groups', related_query_name='added_group_generator_group', to='core.accountsgroup', verbose_name='Добавляемые группы'),
        ),
        migrations.AlterField(
            model_name='groupgenerator',
            name='added_users',
            field=models.ManyToManyField(blank=True, related_name='added_group_generator_users', related_query_name='added_group_generator_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавляемые сотрудники'),
        ),
        migrations.AlterField(
            model_name='groupgenerator',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_generator_creators', related_query_name='group_generator_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='groupgenerator',
            name='excluded_groups',
            field=models.ManyToManyField(blank=True, related_name='excluded_group_generator_groups', related_query_name='excluded_group_generator_group', to='core.accountsgroup', verbose_name='Исключаемые группы'),
        ),
        migrations.AlterField(
            model_name='groupgenerator',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='excluded_group_generator_users', related_query_name='excluded_group_generator_user', to=settings.AUTH_USER_MODEL, verbose_name='Исключаемые сотрудники'),
        ),
    ]
