# Generated by Django 5.1 on 2025-11-29 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_groupgenerator_added_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_page_creators', related_query_name='home_page_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_page_editors', related_query_name='home_page_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главные страницы',
                'permissions': (('add_home_page', 'Может добавить главную страницу'), ('change_home_page', 'Может изменить главную страницу'), ('delete_home_page', 'Может удалить главную страницу'), ('view_home_page', 'Может просматривать главную страницу')),
                'default_permissions': (),
            },
        ),
    ]
