# Generated by Django 5.1 on 2025-12-04 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'default_permissions': (), 'permissions': (('add_home_page', 'Может добавить главную страницу'), ('change_home_page', 'Может изменить главную страницу'), ('delete_home_page', 'Может удалить главную страницу'), ('view_home_page', 'Может просматривать главную страницу')), 'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_page_creators', related_query_name='legal_page_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_page_editors', related_query_name='legal_page_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Страница пользовательского соглашения',
                'verbose_name_plural': 'Страница пользовательского соглашения',
                'permissions': (('add_legal_page', 'Может добавить страницу пользовательского соглашения'), ('change_legal_page', 'Может изменить страницу пользовательского соглашения'), ('delete_legal_page', 'Может удалить страницу пользовательского соглашения'), ('view_legal_page', 'Может просматривать страницу пользовательского соглашения')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_page_creators', related_query_name='policy_page_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_page_editors', related_query_name='policy_page_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Страница политики конфиденциальности',
                'verbose_name_plural': 'Страница политики конфиденциальности',
                'permissions': (('add_policy_page', 'Может добавить страницу политики конфиденциальности'), ('change_policy_page', 'Может изменить главную политики конфиденциальности'), ('delete_policy_page', 'Может удалить главную политики конфиденциальности'), ('view_policy_page', 'Может просматривать главную политики конфиденциальности')),
                'default_permissions': (),
            },
        ),
    ]
