# Generated by Django 5.1 on 2025-12-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homepage_options_legalpage_policypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='agree_to_data_processing',
        ),
        migrations.AddField(
            model_name='account',
            name='agree_to_user_agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие с пользовательским соглашением'),
        ),
        migrations.AlterField(
            model_name='account',
            name='agree_to_privacy_policy',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности и обработки персональных данных'),
        ),
    ]
