# Generated by Django 5.1 on 2025-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_account_agree_to_data_processing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='agree_to_user_agreement',
            new_name='agree_legal',
        ),
        migrations.RemoveField(
            model_name='account',
            name='agree_to_privacy_policy',
        ),
        migrations.AddField(
            model_name='account',
            name='agree_policy',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности'),
        ),
    ]
