# Generated by Django 5.1 on 2025-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_agree_to_user_agreement_account_agree_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='clients', related_query_name='client', to='core.category', verbose_name='Категории'),
        ),
    ]
