# Generated by Django 5.1 on 2025-12-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
