# Generated by Django 5.1 on 2026-01-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='agree_legal',
            new_name='legal_agree',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='agree_policy',
            new_name='policy_agree',
        ),
    ]
