# Generated by Django 5.1 on 2026-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_agree_legal_account_legal_agree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='permissions_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
