# Generated by Django 5.1 on 2026-01-26 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_account_permissions_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgenerator',
            name='days_worked_gte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано от (дней)'),
        ),
        migrations.AlterField(
            model_name='groupgenerator',
            name='days_worked_lte',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано до (дней)'),
        ),
    ]
