# Generated by Django 5.1 on 2026-01-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_groupgenerator_days_worked_gte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupgenerator',
            name='autoupdate',
        ),
    ]
