# Generated by Django 5.1 on 2025-07-18 05:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_groupgenerator_added_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('face_to_face', 'Очное мероприятие'), ('webinar', 'Вебинар'), ('mixed', 'Смешанный формат')], max_length=255, null=True, verbose_name='Формат')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Локация')),
                ('term_type', models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('none', 'Без срока')], max_length=20, null=True, verbose_name='Тип срока')),
                ('term_value', models.IntegerField(blank=True, null=True, verbose_name='Срок')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('admin_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_templates_admins', related_query_name='event_templates_admins', to='core.accountsgroup', verbose_name='Группа ведущих')),
                ('admins', models.ManyToManyField(db_index=True, related_name='event_templates_admins', related_query_name='event_templates_admin', to=settings.AUTH_USER_MODEL, verbose_name='Ведущие')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='event_templates', related_query_name='event_templates', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_template_creators', related_query_name='event_template_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_template_editors', related_query_name='event_template_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'permissions': (('add_event_template', 'Может добавить шаблон мероприятия'), ('change_event_template', 'Может изменить шаблон мероприятия'), ('delete_event_template', 'Может удалить шаблон мероприятия'), ('view_event_template', 'Может просматривать шаблон мероприятия')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('face_to_face', 'Очное мероприятие'), ('webinar', 'Вебинар'), ('mixed', 'Смешанный формат')], max_length=255, null=True, verbose_name='Формат')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Локация')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало по плану')),
                ('deadline', models.BooleanField(default=False, verbose_name='Сроки')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец по плану')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('canceled', 'Отменено'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='planned', max_length=64, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('admin_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_slot_admins', related_query_name='event_slot_admin', to='core.accountsgroup', verbose_name='Группа ведущих')),
                ('admins', models.ManyToManyField(db_index=True, related_name='event_slot_admins', related_query_name='event_slot_admin', to=settings.AUTH_USER_MODEL, verbose_name='Ведущие')),
                ('categories', models.ManyToManyField(blank=True, db_index=True, related_name='event_slots', related_query_name='event_slots', to='core.category', verbose_name='Категории')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_slot_creators', related_query_name='event_slot_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_slot_editors', related_query_name='event_slot_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('event_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_slots', related_query_name='event_slot', to='events.eventtemplate', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'permissions': (('add_event_slot', 'Может добавить мероприятие'), ('change_event_slot', 'Может изменить мероприятие'), ('delete_event_slot', 'Может удалить мероприятие'), ('view_event_slot', 'Может просматривать мероприятие')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ParticipantsGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked_gte', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано от (дней)')),
                ('days_worked_lte', models.IntegerField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Отработано до (дней)')),
                ('autoupdate', models.BooleanField(default=False, verbose_name='Автообновление')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата и время изменения')),
                ('added_groups', models.ManyToManyField(blank=True, related_name='added_participants_generator_groups', related_query_name='added_participants_generator_group', to='core.accountsgroup', verbose_name='Добавляемые группы')),
                ('added_users', models.ManyToManyField(blank=True, related_name='added_participants_generator_users', related_query_name='added_participants_generator_user', to=settings.AUTH_USER_MODEL, verbose_name='Добавляемые сотрудники')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_generator_creators', related_query_name='participants_generator_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_generator_editors', related_query_name='participants_generator_editor', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participants_generator', related_query_name='participants_generator', to='events.eventslot', verbose_name='Мероприятие')),
                ('excluded_groups', models.ManyToManyField(blank=True, related_name='excluded_participants_generator_groups', related_query_name='excluded_participants_generator_group', to='core.accountsgroup', verbose_name='Исключаемые группы')),
                ('excluded_users', models.ManyToManyField(blank=True, related_name='excluded_participants_generator_users', related_query_name='excluded_participants_generator_user', to=settings.AUTH_USER_MODEL, verbose_name='Исключаемые сотрудники')),
            ],
            options={
                'verbose_name': 'Генератор участников',
                'verbose_name_plural': 'Генераторы участников',
                'permissions': (('add_participants_generator', 'Может добавить генератор участников'), ('change_participants_generator', 'Может изменить генератор участников'), ('delete_participants_generator', 'Может удалить генератор участников'), ('view_participants_generator', 'Может просматривать генератор участников')),
                'default_permissions': (),
            },
        ),
    ]
