# Generated by Django 5.1 on 2025-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='event_template_avatars/', verbose_name='Аватар'),
        ),
    ]
