# Generated by Django 5.1 on 2025-07-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventtemplate_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='event_slot_avatars/', verbose_name='Аватар'),
        ),
    ]
