# Generated by Django 5.1 on 2025-08-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventslot_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'default_permissions': (), 'permissions': (('add_event_template', 'Может добавить шаблон мероприятия'), ('change_event_template', 'Может изменить шаблон мероприятия'), ('delete_event_template', 'Может удалить шаблон мероприятия'), ('view_event_template', 'Может просматривать шаблон мероприятия')), 'verbose_name': 'Шаблон мероприятия', 'verbose_name_plural': 'Шаблоны мероприятий'},
        ),
    ]
