# Generated by Django 5.1 on 2025-08-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventtemplate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='term_type',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='term_value',
        ),
    ]
