# Generated by Django 5.1 on 2025-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventtemplate_term_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='term_type',
            field=models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('none', 'Без срока')], max_length=20, null=True, verbose_name='Тип срока'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='term_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок'),
        ),
    ]
