# Generated by Django 5.1 on 2025-08-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventtemplate_term_type_eventtemplate_term_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventslot',
            options={'default_permissions': (), 'permissions': (('add_event_slot', 'Может добавить слот'), ('change_event_slot', 'Может изменить слот'), ('delete_event_slot', 'Может удалить слот'), ('view_event_slot', 'Может просматривать слот')), 'verbose_name': 'Слот', 'verbose_name_plural': 'Слоты'},
        ),
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'default_permissions': (), 'permissions': (('add_event_template', 'Может добавить мероприятия'), ('change_event_template', 'Может изменить мероприятия'), ('delete_event_template', 'Может удалить мероприятия'), ('view_event_template', 'Может просматривать мероприятия')), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
