# Generated by Django 5.1 on 2025-08-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventslot_options_alter_eventtemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventslot',
            options={'default_permissions': (), 'permissions': (('add_event_slot', 'Может добавить мероприятие'), ('change_event_slot', 'Может изменить мероприятие'), ('delete_event_slot', 'Может удалить мероприятие'), ('view_event_slot', 'Может просматривать мероприятие')), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'default_permissions': (), 'permissions': (('add_event_template', 'Может добавить шаблон мероприятия'), ('change_event_template', 'Может изменить шаблон мероприятия'), ('delete_event_template', 'Может удалить шаблон мероприятия'), ('view_event_template', 'Может просматривать шаблон мероприятия')), 'verbose_name': 'Шаблон мероприятия', 'verbose_name_plural': 'Шаблоны мероприятий'},
        ),
    ]
