# Generated by Django 5.1 on 2025-08-21 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventslot_options_alter_eventtemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslot',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_slots', related_query_name='event_slot', to='events.eventtemplate', verbose_name='Шаблон мероприятия'),
        ),
    ]
