# Generated by Django 5.1 on 2025-08-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventslot_event_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'default_permissions': (), 'permissions': (('add_event_template', 'Может добавить шаблон мероприятия'), ('change_event_template', 'Может изменить шаблон мероприятия'), ('delete_event_template', 'Может удалить шаблон мероприятия'), ('view_event_template', 'Может просматривать шаблон мероприятия')), 'verbose_name': 'Программа мероприятия', 'verbose_name_plural': 'Программы мероприятий'},
        ),
    ]
