# Generated by Django 5.1 on 2025-08-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventtemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'default_permissions': (), 'permissions': (('add_event_template', 'Может добавить мероприятие'), ('change_event_template', 'Может изменить мероприятие'), ('delete_event_template', 'Может удалить мероприятие'), ('view_event_template', 'Может просматривать мероприятие')), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='admin_group',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='format',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='link',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventslot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='term_type',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='term_value',
        ),
        migrations.AddField(
            model_name='eventslot',
            name='number_of_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='eventslot',
            name='event_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_slots', related_query_name='event_slot', to='events.eventtemplate', verbose_name='Мероприятие'),
        ),
    ]
