# Generated by Django 5.1 on 2025-08-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventslot',
            options={'default_permissions': (), 'permissions': (('add_event_slot', 'Может добавить слот мероприятия'), ('change_event_slot', 'Может изменить слот мероприятия'), ('delete_event_slot', 'Может удалить слот мероприятия'), ('view_event_slot', 'Может просматривать слот мероприятия')), 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
