# Generated by Django 5.1 on 2025-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventslot',
            options={'default_permissions': (), 'permissions': (('add_event_slot', 'Может добавить слот мероприятия'), ('change_event_slot', 'Может изменить слот мероприятия'), ('delete_event_slot', 'Может удалить слот мероприятия'), ('view_event_slot', 'Может просматривать слот мероприятия')), 'verbose_name': 'Слот мероприятия', 'verbose_name_plural': 'Слот мероприятия'},
        ),
        migrations.AddField(
            model_name='eventslot',
            name='registration',
            field=models.BooleanField(default=False, verbose_name='Регистрация открыта'),
        ),
    ]
