# Generated by Django 5.1 on 2025-09-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventslot_options_eventslot_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
