# Generated by Django 5.1 on 2025-09-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventslot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventslot',
            name='name',
        ),
    ]
