# Generated by Django 5.1 on 2025-12-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_eventslot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='self_assignment',
            field=models.BooleanField(default=False, verbose_name='Самоназначение'),
        ),
        migrations.DeleteModel(
            name='ParticipantsGenerator',
        ),
    ]
