# Generated by Django 5.1 on 2025-12-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventslot_self_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventslot',
            name='self_assignment',
        ),
    ]
